const router = require('express').Router();
const path   = require('path');
const fs     = require('fs');
const crypto = require('crypto');
const Publication = require('../models/Publication');
const Font        = require('../models/Font');
const { getTemplateHtml } = require('../utils/templateCache');
const {
  safeJsonForScript,
  safeColor,
  safeFontFamily,
  isSafeTemplateName,
  safeCssUrl,
  safeHttpUrl,
} = require('../utils/htmlSafe');

const PROD = process.env.NODE_ENV === 'production';

/* ── BubbleFont Cloudinary CDN URLs ──────────────────────────────
   Loaded once at startup from bubble-font-urls.json (generated by
   uploadBubbleLetters.js).  Falls back gracefully if not present.
   ─────────────────────────────────────────────────────────────── */
let BUBBLE_LETTER_URLS = {};
try {
  const urlsFile = path.join(__dirname, '../bubble-font-urls.json');
  if (fs.existsSync(urlsFile)) {
    BUBBLE_LETTER_URLS = JSON.parse(fs.readFileSync(urlsFile, 'utf8'));
  }
} catch {}

const BUBBLE_TEMPLATES = new Set(['birthday', 'collective-family', 'collective-pro', 'special']);

const WALL_DEFAULTS = {
  'wall-of-wishes':        { primaryColor: '#E11D48', accentColor: '#E11D48' },
  'wall-of-wishes-modern': { primaryColor: '#7C5CC9', accentColor: '#7C5CC9' },
  'wall-of-wishes-3d':     { primaryColor: '#c9a84c', accentColor: '#e05574' },
  'wall-of-wishes-space':  { primaryColor: '#ff7055', accentColor: '#ff3d6e' },
};
const LEGACY_SCHEMA_DEFAULTS = { primaryColor: '#ff69b4', accentColor: '#ffb347' };

const GOOGLE_FONTS_MAP = {
  'Work Sans':        'Work+Sans:wght@300;400;500;600;700',
  'Inter':            'Inter:wght@300;400;500;600;700',
  'Playfair Display': 'Playfair+Display:wght@400;500;600;700',
  'Pacifico':         'Pacifico',
  'Dancing Script':   'Dancing+Script:wght@400;500;600;700',
  'Montserrat':       'Montserrat:wght@300;400;500;600;700',
  'Poppins':          'Poppins:wght@300;400;500;600;700',
  'Lato':             'Lato:wght@300;400;700',
  'Raleway':          'Raleway:wght@300;400;500;600;700',
  'Nunito':           'Nunito:wght@300;400;500;600;700',
};

function optimizeCloudinaryUrl(url, transforms = 'f_auto,q_auto:good,w_1400,c_limit') {
  if (!url || !url.includes('res.cloudinary.com')) return url;
  if (url.includes('/upload/f_') || url.includes('/upload/q_') || url.includes('/upload/w_')) return url;
  return url.replace('/upload/', `/upload/${transforms}/`);
}

/* ── CSP ─────────────────────────────────────────────────────
   Template HTML contient inline scripts + styles → 'unsafe-inline'
   obligatoire, mais on restreint tout le reste au strict minimum.
   ──────────────────────────────────────────────────────────── */
const CSP = [
  "default-src 'self' https: data: blob:",
  "script-src 'self' 'unsafe-inline' https:",
  "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
  "font-src 'self' https://fonts.gstatic.com https://res.cloudinary.com data:",
  "img-src 'self' https: data: blob:",
  "media-src 'self' https: blob:",
  "connect-src 'self' https:",
  "object-src 'none'",
  "base-uri 'self'",
  "frame-ancestors 'self' http://localhost:3000 http://localhost:5173 https://app.mykado.store https://mykado.store",
].join('; ');

function sendError(res, status, publicMsg, err) {
  if (err) console.error('[serve]', err);
  res.status(status).setHeader('Content-Type', 'text/html; charset=utf-8');
  return res.send(`<!DOCTYPE html><html><body style="font-family:sans-serif;text-align:center;padding:80px;background:#fafafa"><h1>${status}</h1><p>${publicMsg}</p></body></html>`);
}

router.get('/:templateName/:customName', async (req, res) => {
  res.setHeader('Content-Security-Policy', CSP);
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

  const { templateName, customName } = req.params;

  if (!isSafeTemplateName(templateName)) {
    return sendError(res, 400, 'Nom de template invalide.');
  }

  try {
    const pub = await Publication.findOne({ templateName, customName }).lean();

    if (!pub) {
      return sendError(res, 404, 'Aucune création trouvée à cette adresse.');
    }

    const isPreview = req.query.preview === '1';
    const isWallTemplate = pub.templateName.startsWith('wall-of-wishes');
    const isWallFreemium = isWallTemplate && !pub.published;

    if (!pub.published && !isPreview && !isWallFreemium) {
      res.status(410);
      res.setHeader('Cache-Control', 'no-store');
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(`
        <html>
        <head>
          <meta charset="UTF-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <title>Lien non disponible</title>
          <style>
            body { margin:0; font-family:'Segoe UI',system-ui,sans-serif;
              background:#f8f8f8; display:flex; align-items:center;
              justify-content:center; min-height:100vh; }
            .card { background:#fff; border-radius:16px; padding:48px 36px;
              text-align:center; max-width:360px;
              box-shadow:0 4px 24px rgba(0,0,0,0.08); }
            h1 { font-size:1.3rem; color:#1a1a1a; margin:0 0 10px; font-weight:700; }
            p { color:#888; font-size:0.9rem; line-height:1.6; margin:0; }
          </style>
        </head>
        <body>
          <div class="card">
            <h1>Ce lien n'est plus disponible</h1>
            <p>Cette création a été dépubliée par son auteur.</p>
          </div>
        </body>
        </html>
      `);
    }

    let html = await getTemplateHtml(pub.templateName);
    if (!html) return sendError(res, 404, 'Template introuvable.');

    /* ── Custom fonts from DB (rare, cached in-memory) ─── */
    let fontFaceCSS = '';
    try {
      const customFonts = await Font.find({}).lean();
      if (customFonts.length) {
        fontFaceCSS = customFonts.map(f => {
          const name = safeFontFamily(f.name, '');
          const url  = safeCssUrl(f.url);
          const fmt  = safeFontFamily(f.format, 'woff2');
          if (!name || !url) return '';
          return `@font-face { font-family: '${name}'; src: url('${url}') format('${fmt}'); font-display: swap; }`;
        }).filter(Boolean).join('\n');
      }
    } catch {}

    /* ── BubbleFont per-letter CDN loading ───────────── */
    let bubbleFontPreloads = '';
    let bubbleFontFaces    = '';
    if (BUBBLE_TEMPLATES.has(pub.templateName) && Object.keys(BUBBLE_LETTER_URLS).length > 0) {
      const nameText    = String((pub.data && pub.data.name) || '');
      const neededChars = [...new Set(('HBD' + nameText).toUpperCase().split('').filter(c => /[A-Z]/.test(c)))].sort();

      const preloadTags = [];
      const fontFaceRules = [];

      for (const letter of neededChars) {
        const url = BUBBLE_LETTER_URLS[letter];
        if (!url || !safeCssUrl(url)) continue;
        const codePoint = `U+${letter.charCodeAt(0).toString(16).padStart(4, '0').toUpperCase()}`;
        preloadTags.push(`<link rel="preload" href="${url}" as="font" type="font/woff2" crossorigin>`);
        fontFaceRules.push(
          `@font-face{font-family:'BubbleFont';src:url('${url}')format('woff2');unicode-range:${codePoint};font-display:block;}`
        );
      }

      bubbleFontPreloads = preloadTags.join('\n  ');
      bubbleFontFaces    = fontFaceRules.join('\n');
    }

    const s     = pub.style || {};
    const scale = s.fontSize === 'small' ? '0.85' : s.fontSize === 'large' ? '1.15' : '1';
    const bgs   = s.backgrounds || {};

    /* ── CSS: wall background + palette (étape 2 flow murs) ─────
       Consomme style.wallBackground / wallBackgroundInk / wallAccent /
       wallBackgroundSize. Whitelist stricte pour éviter toute injection CSS.
       - 'cover' : le bg couvre le viewport et reste en place au scroll
       - 'tile'  : le bg se répète (background-repeat: repeat) */
    const wallBgLines = [];
    if (isWallTemplate) {
      const rawBg = String(s.wallBackground || '').trim();
      const rawInk = safeColor(s.wallBackgroundInk, '');
      const rawAccent = safeColor(s.wallAccent, '');
      const rawSize = (s.wallBackgroundSize === 'tile') ? 'tile' : 'cover';

      let safeBg = '';
      if (!/[;<>}]/.test(rawBg) && (/^(?:linear|radial|conic)-gradient/i.test(rawBg) || /^#[0-9a-f]{3,8}$/i.test(rawBg) || /^url\(/i.test(rawBg))) {
        safeBg = rawBg;
      }

      if (safeBg) {
        wallBgLines.push(`  --wall-bg: ${safeBg};`);
        if (rawSize === 'tile') {
          wallBgLines.push(`  --wall-bg-size: auto;`);
          wallBgLines.push(`  --wall-bg-repeat: repeat;`);
        } else {
          wallBgLines.push(`  --wall-bg-size: cover;`);
          wallBgLines.push(`  --wall-bg-repeat: no-repeat;`);
        }
      }
      if (rawInk)    wallBgLines.push(`  --wall-ink: ${rawInk};`);
      if (rawAccent) {
        wallBgLines.push(`  --wall-accent: ${rawAccent};`);
        /* Les templates hardcodent --pin-btn (boutons primaires) et
           --pin-cag-fill (accents/gold). On les fait suivre l'accent utilisateur
           pour que la palette choisie s'applique vraiment aux CTA. */
        wallBgLines.push(`  --pin-btn: ${rawAccent};`);
        wallBgLines.push(`  --pin-cag-fill: ${rawAccent};`);
      }
      const rawAccentInk = safeColor(s.paletteAccentText || '', '');
      if (rawAccentInk) wallBgLines.push(`  --pin-btn-ink: ${rawAccentInk};`);
      /* Bannière (#wall-cover) : lit --cover-image (gradient) et --cover-ink (couleur texte).
         Sources : data.bannerTint (gradient de l'occasion) + data.bannerInk (contraste). */
      const rawBanner = String((pub.data && pub.data.bannerTint) || '').trim();
      let safeBanner = '';
      if (!/[;<>}]/.test(rawBanner) && (/^(?:linear|radial|conic)-gradient/i.test(rawBanner) || /^#[0-9a-f]{3,8}$/i.test(rawBanner) || /^url\(/i.test(rawBanner))) {
        safeBanner = rawBanner;
      }
      if (safeBanner) wallBgLines.push(`  --cover-image: ${safeBanner};`);
      const rawBannerInk = safeColor((pub.data && pub.data.bannerInk) || '', '');
      if (rawBannerInk) wallBgLines.push(`  --cover-ink: ${rawBannerInk};`);
    }

    /* ── CSS: section background variables (whitelisted) ─── */
    const bgCssLines = [];
    Object.entries(bgs).forEach(([rawKey, bg]) => {
      if (!bg || !bg.value) return;
      const key = String(rawKey).replace(/[^a-zA-Z0-9-]/g, '');
      if (!key) return;

      let bgValue;
      if (bg.type === 'color')    bgValue = safeColor(bg.value, '');
      else if (bg.type === 'gradient') {
        // Gradients: must start with linear-gradient/radial-gradient/conic-gradient
        // and contain no `;`, `}`, `<`, `>`
        const g = String(bg.value).trim();
        if (!/[;<>}]/.test(g) && /^(?:linear|radial|conic)-gradient/i.test(g)) bgValue = g;
      }
      else if (bg.type === 'image')    {
        const url = safeCssUrl(optimizeCloudinaryUrl(bg.value));
        if (url) bgValue = `url("${url}") center/cover no-repeat`;
      }

      if (bgValue) {
        bgCssLines.push(`  --bg-${key}: ${bgValue};`);
        if (bg.overlay != null && /^[\d.,\s%rgbahsl()#]+$/i.test(String(bg.overlay))) {
          bgCssLines.push(`  --bg-${key}-overlay: ${bg.overlay};`);
        }
        if (bg.blur != null && Number.isFinite(Number(bg.blur))) {
          bgCssLines.push(`  --bg-${key}-blur: ${Number(bg.blur)}px;`);
        }
      }
    });

    /* ── Fonts (validated) ─── */
    const chosenFont = safeFontFamily(s.fontFamily, 'Work Sans');
    const gFontQuery = GOOGLE_FONTS_MAP[chosenFont];
    const googleFontLink = gFontQuery
      ? `<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=${gFontQuery}&display=swap" rel="stylesheet">`
      : '';
    if (googleFontLink) {
      html = html.replace('</head>', `${googleFontLink}\n</head>`);
    }

    if (bubbleFontPreloads) {
      html = html.replace('<head>', `<head>\n  ${bubbleFontPreloads}`);
    }

    /* ── Colors: wall smart fallback + validation ─── */
    let wallPrimary, wallAccent;
    if (isWallTemplate) {
      const tplDef = WALL_DEFAULTS[pub.templateName] || WALL_DEFAULTS['wall-of-wishes'];
      const rawAcc = safeColor(s.wallAccent, '');
      const userPrimary = (s.primaryColor && s.primaryColor !== LEGACY_SCHEMA_DEFAULTS.primaryColor) ? s.primaryColor : null;
      const userAccent  = (s.accentColor  && s.accentColor  !== LEGACY_SCHEMA_DEFAULTS.accentColor)  ? s.accentColor  : null;
      wallPrimary = rawAcc || safeColor(userPrimary, tplDef.primaryColor);
      wallAccent  = rawAcc || safeColor(userAccent,  tplDef.accentColor);
    } else {
      wallPrimary = safeColor(s.primaryColor, '#ff69b4');
      wallAccent  = safeColor(s.accentColor,  '#ffb347');
    }
    const textColor = safeColor(s.textColor, '#333333');
    const textMuted = safeColor(s.textMuted, '#888888');

    /* ── Admin banner (wall only) ─── */
    let isAdmin = false;
    let adminReturnUrl = '';
    if (isWallTemplate) {
      try {
        const token = req.cookies?.ww_admin_token;
        if (token) {
          const decoded = require('jsonwebtoken').verify(token, process.env.JWT_SECRET);
          if (decoded) {
            isAdmin = true;
            const appOrigin = process.env.APP_URL || (PROD ? 'https://app.mykado.store' : 'http://localhost:3000');
            adminReturnUrl = `${appOrigin}/ewish-admin/wall/${String(pub._id)}`;
          }
        }
      } catch {}
    }

    /* ── Publication data (safely serialized) ─── */
    const jarCfg = pub.jarConfig || null;
    const rawData = pub.data || {};
    const publicData = jarCfg ? { ...rawData, jarConfig: jarCfg } : { ...rawData };
    publicData.publicationId = String(pub._id);
    publicData.apiBase = process.env.API_BASE_URL || '';
    publicData.wishesEnabled = pub.cagnotteConfig?.wishesEnabled !== false;
    publicData.isPrivate = pub.cagnotteConfig?.isPrivate || (isWallTemplate && (pub.data?.isPrivate || false));
    publicData.accessCode = pub.cagnotteConfig?.accessCode || (isWallTemplate ? pub.data?.accessCode : '') || '';
    publicData.requireModeration = pub.cagnotteConfig?.requireModeration || false;
    publicData.isPaid = pub.isPaid || false;
    publicData.minContribution = pub.cagnotteConfig?.minContribution || 0;
    publicData.maxContribution = pub.cagnotteConfig?.maxContribution || 0;
    publicData.isAdmin = isAdmin;
    publicData.adminReturnUrl = adminReturnUrl;
    publicData.previewMode = isPreview;
    publicData.skipIntro = req.query.noanim === '1';
    publicData.cagnotte = pub.cagnotteConfig?.enabled ? {
      enabled: true,
      name: pub.cagnotteConfig.description || '',
      goal: pub.cagnotteConfig.goal || 0,
      emoji: '🎁',
      collected: 0,
      contributors: 0,
      minAmount: pub.cagnotteConfig.minContribution || 0,
      maxAmount: pub.cagnotteConfig.maxContribution || 0,
    } : null;

    const meta = {
      id:           String(pub._id),
      title:        pub.title,
      templateName: pub.templateName,
      customName:   pub.customName,
    };
    const branding = {
      show: Boolean(pub.showBranding),
      url: safeHttpUrl(pub.brandingUrl || process.env.BRANDING_URL || 'https://wa.me/+2290159571057'),
      label: pub.brandingText || 'Crée le tien sur myKado ✨',
    };
    // Whitelist alphanumeric + tirets (label court, pas de sortie CSS/JS possible)
    const confettiType = (typeof s.confettiType === 'string' && /^[a-zA-Z0-9-]{1,30}$/.test(s.confettiType))
      ? s.confettiType : 'default';

    const injection = `
<style>
${bubbleFontFaces ? bubbleFontFaces + '\n' : ''}${fontFaceCSS ? fontFaceCSS + '\n' : ''}  :root {
    --primary:    ${wallPrimary};
    --accent:     ${wallAccent};
    --gold:       ${wallPrimary};
    --rose:       ${wallAccent};
    --font:       '${chosenFont}', sans-serif;
    --font-b:     '${chosenFont}', sans-serif;
    --fs-scale:   ${scale};
    --text-color: ${textColor};
    --text-muted: ${textMuted};
${bgCssLines.join('\n')}
${wallBgLines.join('\n')}
  }
  body { font-family: var(--font) !important; }
</style>
<script>
  window.__WW_DATA__  = ${safeJsonForScript(publicData)};
  window.__WW_STYLE__ = ${safeJsonForScript(pub.style || {})};
  window.__WW_META__  = ${safeJsonForScript(meta)};
  window.__WW_API_BASE__ = ${safeJsonForScript(process.env.API_BASE_URL || '')};
  window.__WW_BRANDING__ = ${safeJsonForScript(branding)};
  window.__WW_DECO__     = ${safeJsonForScript(pub.decorations || [])};
  window.__WW_WIDGETS__  = ${safeJsonForScript(pub.widgets || [])};
  window.__WW_PHOTO_TRANSFORMS__ = ${safeJsonForScript(pub.photoTransforms || {})};
  window.__WW_CONFETTI_TYPE__    = ${safeJsonForScript(confettiType)};
<\/script>`;

    /* Inject engine + payload avant </head>. Ordre : engine d'abord (dispo pour tout) */
    if (!html.includes('ww-engine.js')) {
      html = html.replace('</head>', '<script src="/templates/shared/ww-engine.js"><\/script>\n</head>');
    }
    html = html.replace('</head>', injection + '\n</head>');

    /* ── Compteur de vues (single $inc) ─────────────── */
    if (!isPreview) {
      Publication.findByIdAndUpdate(pub._id, {
        $inc: { views: 1 },
        lastViewedAt: new Date(),
      }).catch(() => {});
    }

    /* ── Cache-Control + ETag ────────────────────────
       Public si publié + non-private, sinon private/no-store.
       ETag basé sur updatedAt permet un 304 sans regénérer. */
    const isPrivate = publicData.isPrivate || !!publicData.accessCode || isPreview;
    if (isPrivate) {
      res.setHeader('Cache-Control', 'private, no-store');
    } else {
      res.setHeader('Cache-Control', 'public, max-age=60, stale-while-revalidate=300');
      const etag = `W/"${crypto.createHash('sha1').update(String(pub._id) + ':' + new Date(pub.updatedAt || pub.createdAt || 0).getTime()).digest('base64')}"`;
      res.setHeader('ETag', etag);
      if (req.headers['if-none-match'] === etag) {
        return res.status(304).end();
      }
    }

    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.send(html);
  } catch (e) {
    return sendError(res, 500, 'Une erreur est survenue.', e);
  }
});

module.exports = router;
