/**
 * Seed corrector — fields en français pour tous les templates
 * Usage : node server/seeds/seedTemplates.js
 *   ou  : npm run seed:templates  (depuis server/)
 *
 * Ce script upsert chaque template avec :
 *   - labels de champs en français
 *   - données par défaut (defaultData) en français
 *   - métadonnées (label, description, highlights, etc.)
 * Il ne supprime PAS les vœux ni les publications existantes.
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Template = require('../models/Template');

/* ─────────────────────────────────────────────────────────────
   Définition des templates
───────────────────────────────────────────────────────────── */
const TEMPLATES = [

  /* ── birthday ───────────────────────────────────────────── */
  {
    name: 'birthday',
    label: 'Joyeux Anniversaire',
    description: "Animation complète avec photos, musique et vœux personnalisés. L'incontournable.",
    price: 1000,
    creditsRequired: 2,
    emoji: '🎂',
    gradient: 'linear-gradient(135deg,#ffb4d1,#f7d59e)',
    highlights: ["Jusqu'à 24 photos animées", 'Musique personnalisée (MP3)', '3 styles de typographie', 'Lien privé + QR code'],
    tags: ['anniversaire', 'classique'],
    sortOrder: 1,
    active: true,
    featured: true,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',    type: 'text',      section: 'Intro',     placeholder: 'Sophie',                                    required: true  },
      { key: 'greeting',       label: "Message d'accueil",         type: 'text',      section: 'Intro',     placeholder: 'Coucou'                                                         },
      { key: 'greetingText',   label: 'Note personnelle',          type: 'text',      section: 'Intro',     placeholder: 'Tu comptes énormément pour nous !'                              },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)',type: 'url',       section: 'Musique',   placeholder: 'https://... .mp3'                                               },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',     type: 'starttime', section: 'Musique'                                                                                   },
      { key: 'albumArt',       label: "Pochette de l'album (URL)", type: 'url',       section: 'Musique',   placeholder: 'https://... .jpg'                                               },
      { key: 'trackTitle',     label: 'Titre de la musique',       type: 'text',      section: 'Musique',   placeholder: 'Happy Birthday'                                                 },
      { key: 'trackArtist',    label: 'Artiste',                   type: 'text',      section: 'Musique',   placeholder: 'Stevie Wonder'                                                  },
      { key: 'musicHint',      label: 'Indication musique',        type: 'text',      section: 'Musique',   placeholder: "C'est mieux avec de la musique 🎶"                              },
      { key: 'text1',          label: "Accroche principale",       type: 'text',      section: 'Message',   placeholder: "C'est ton anniversaire !!! 🎉"                                  },
      { key: 'textInChatBox',  label: 'Message WhatsApp',          type: 'textarea',  section: 'Message',   placeholder: "Joyeux anniversaire !!! 🎉 Je suis tellement content(e) que tu existes…" },
      { key: 'text2',          label: "Phrase d'histoire 1",       type: 'text',      section: 'Histoire',  placeholder: 'On a cherché les mots.'                                         },
      { key: 'text3',          label: "Phrase d'histoire 2",       type: 'text',      section: 'Histoire',  placeholder: 'On en a trouvé beaucoup.'                                       },
      { key: 'text4',          label: "Phrase d'histoire 3",       type: 'text',      section: 'Histoire',  placeholder: 'Mais surtout, on voulait dire'                                  },
      { key: 'text4Adjective', label: "Mot clé de l'histoire",     type: 'text',      section: 'Histoire',  placeholder: 'merci'                                                          },
      { key: 'text5Entry',     label: 'Intro phrase finale',       type: 'text',      section: 'Histoire',  placeholder: 'Parce que,'                                                     },
      { key: 'text5Content',   label: 'Phrase finale',             type: 'text',      section: 'Histoire',  placeholder: 'Tu es irremplaçable'                                            },
      { key: 'smiley',         label: 'Emoji principal',           type: 'text',      section: 'Histoire',  placeholder: ':)'                                                             },
      { key: 'wishHeading',    label: 'Titre du vœu',              type: 'text',      section: 'Vœu',       placeholder: 'Joyeux Anniversaire !',                     required: true      },
      { key: 'wishText',       label: 'Sous-titre du vœu',         type: 'text',      section: 'Vœu',       placeholder: 'Avec tout notre amour 💖'                                       },
      { key: 'outroText',      label: 'Message de fin',            type: 'text',      section: 'Outro',     placeholder: 'Reviens nous dire si tu as aimé.'                               },
      { key: 'replayText',     label: 'Texte du bouton revoir',    type: 'text',      section: 'Outro',     placeholder: 'Clique pour revoir ↺'                                           },
      { key: 'outroSmiley',    label: 'Emoji de fin',              type: 'text',      section: 'Outro',     placeholder: '🥰'                                                             },
    ],
    defaultData: {
      greeting: 'Coucou',
      name: 'Sally',
      greetingText: 'Joli prénom btw !',
      musicHint: "C'est mieux avec de la musique 🎶",
      text1: "C'est ton anniversaire !!! 🎉",
      textInChatBox: "Joyeux anniversaire !!! 🎉 Je suis tellement content(e) que tu existes… T'as pas idée !",
      trackTitle: 'Happy Birthday',
      trackArtist: 'Naza',
      text2: "C'est ce que j'allais faire..",
      text3: 'Mais..',
      text4: 'J\' ai voulu faire quelque chose de ',
      text4Adjective: 'spécial',
      text5Entry: 'Parce que,',
      text5Content: 'Tu es Spéciale',
      smiley: ':)',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'From my heart',
      outroText: "J'espère que tu as kiffé !",
      replayText: 'Revoir ↺',
      outroSmiley: ':)',
    },
    defaultStyle: { primaryColor: '#e05574', accentColor: '#c9a84c', fontFamily: 'Work Sans', fontSize: 'medium', theme: 'light' },
  },

  /* ── wall-of-wishes ─────────────────────────────────────── */
  {
    name: 'wall-of-wishes',
    label: 'Mur de vœux',
    description: "Un mur interactif où chacun colle son message — comme des post-its numériques.",
    price: 5000,
    creditsRequired: 10,
    emoji: '💌',
    gradient: 'linear-gradient(135deg,#fdf6c3,#fce4ec,#ede7f6)',
    highlights: ["Jusqu'à 30 contributeurs", 'Modération avant publication', '6 couleurs de post-it', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif'],
    sortOrder: 2,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'Prénom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Partagez ce lien — laissez votre message ici.' },
    ],
    defaultData: {
      titleName: 'Prénom',
      subtitle: 'Partagez ce lien — chacun peut laisser son mot sur ce mur.',
    },
    defaultStyle: { primaryColor: '#c9a84c', accentColor: '#e05574', fontFamily: 'Inter', fontSize: 'medium', theme: 'light' },
  },

  /* ── special ────────────────────────────────────────────── */
  {
    name: 'special',
    label: 'Vœu Spécial',
    description: "Pour les occasions uniques. Effets premium, thème sur-mesure, vidéo HD.",
    price: 1000,
    creditsRequired: 2,
    emoji: '✦',
    gradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
    highlights: ['Thème sur-mesure', 'Particules & transitions premium', 'Export vidéo MP4 HD', 'Photos illimitées'],
    tags: ['premium', 'spécial'],
    sortOrder: 3,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',    placeholder: 'Kofi',                                                     required: true },
      { key: 'greeting',       label: "Message d'accueil",          type: 'text',      section: 'Intro',    placeholder: 'Coucou'                                                                         },
      { key: 'greetingText',   label: 'Note personnelle',           type: 'text',      section: 'Intro',    placeholder: "On a cherché et on t'a trouvé."                                                 },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                                               },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',      type: 'starttime', section: 'Musique'                                                                                                  },
      { key: 'albumArt',       label: "Pochette de l'album (URL)",  type: 'url',       section: 'Musique',  placeholder: 'https://... .jpg'                                                               },
      { key: 'trackTitle',     label: 'Titre de la musique',        type: 'text',      section: 'Musique',  placeholder: 'Gold'                                                                           },
      { key: 'trackArtist',    label: 'Artiste',                    type: 'text',      section: 'Musique',  placeholder: 'Spandau Ballet'                                                                 },
      { key: 'musicHint',      label: 'Indication musique',         type: 'text',      section: 'Musique',  placeholder: "C'est mieux avec de la musique 🎶"                                              },
      { key: 'text1',          label: 'Accroche avant la recherche',type: 'text',      section: 'Google',   placeholder: 'On a fait une recherche… 🔍'                                                    },
      { key: 'searchQuery',    label: 'Requête Google',             type: 'text',      section: 'Google',   placeholder: 'meilleure personne du monde'                                                    },
      { key: 'result1Title',   label: 'Titre résultat #1',          type: 'text',      section: 'Google',   placeholder: 'La personne la plus exceptionnelle recensée à ce jour'                          },
      { key: 'result1Snippet', label: 'Extrait résultat #1',        type: 'textarea',  section: 'Google',   placeholder: "Après analyse de 8 milliards de profils, les experts s'accordent…"             },
      { key: 'result1Domain',  label: 'Domaine résultat #1',        type: 'text',      section: 'Google',   placeholder: 'levivant.monde'                                                                 },
      { key: 'result1Rating',  label: 'Note résultat #1',           type: 'text',      section: 'Google',   placeholder: '5,0 · Note de l\'univers entier'                                                },
      { key: 'result2Title',   label: 'Titre résultat #2',          type: 'text',      section: 'Google',   placeholder: 'Définition de "parfaite" — voir aussi : elle'                                   },
      { key: 'result2Snippet', label: 'Extrait résultat #2',        type: 'textarea',  section: 'Google',   placeholder: 'Les dictionnaires du monde entier ont récemment mis à jour leur définition…'    },
      { key: 'result3Title',   label: 'Titre résultat #3',          type: 'text',      section: 'Google',   placeholder: 'Record mondial officiel — Personne la plus formidable'                          },
      { key: 'result3Snippet', label: 'Extrait résultat #3',        type: 'textarea',  section: 'Google',   placeholder: 'Le Guinness World Records certifie officiellement…'                             },
      { key: 'text2',          label: "Phrase de transition 1",     type: 'text',      section: 'Histoire', placeholder: 'On a cherché partout.'                                                          },
      { key: 'text3',          label: "Phrase de transition 2",     type: 'text',      section: 'Histoire', placeholder: 'Des milliards de résultats.'                                                    },
      { key: 'text4',          label: "Phrase de transition 3",     type: 'text',      section: 'Histoire', placeholder: 'Et le premier résultat, c\'était'                                               },
      { key: 'text4Adjective', label: 'Adjectif clé',               type: 'text',      section: 'Histoire', placeholder: 'toi'                                                                            },
      { key: 'text5Entry',     label: 'Intro phrase finale',        type: 'text',      section: 'Histoire', placeholder: 'Parce que,'                                                                     },
      { key: 'text5Content',   label: 'Phrase finale',              type: 'text',      section: 'Histoire', placeholder: 'Tu es unique'                                                                   },
      { key: 'smiley',         label: 'Emoji principal',            type: 'text',      section: 'Histoire', placeholder: '🎂'                                                                             },
      { key: 'wishHeading',    label: 'Titre du vœu',               type: 'text',      section: 'Vœu',      placeholder: 'Joyeux Anniversaire !',                             required: true             },
      { key: 'wishText',       label: 'Sous-titre du vœu',          type: 'text',      section: 'Vœu',      placeholder: 'Le meilleur reste à venir 🚀'                                                   },
      { key: 'outroText',      label: 'Message de fin',             type: 'text',      section: 'Outro',    placeholder: "On espère que tu as aimé."                                                      },
      { key: 'replayText',     label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',    placeholder: 'Revoir ↺'                                                                       },
      { key: 'outroSmiley',    label: 'Emoji de fin',               type: 'text',      section: 'Outro',    placeholder: '🎉'                                                                             },
    ],
    defaultData: {
      greeting: 'Coucou',
      name: 'Sally',
      greetingText: "On a cherché et on t'a trouvé.",
      musicHint: "C'est mieux avec de la musique 🎶",
      text1: 'On a fait une recherche… 🔍',
      trackTitle: 'Happy Birthday',
      trackArtist: 'Naza',
      searchQuery: 'meilleure personne du monde',
      result1Title: 'La personne la plus exceptionnelle recensée à ce jour',
      result1Snippet: "Après analyse de 8 milliards de profils, les experts s'accordent sur un résultat sans appel.",
      result1Domain: 'levivant.monde',
      result1Rating: "5,0 · Note de l'univers entier",
      result2Title: 'Définition de "parfaite" — voir aussi : elle',
      result2Snippet: "Les dictionnaires du monde entier ont récemment mis à jour leur définition de \"parfaite\" pour y inclure une photo.",
      result3Title: 'Record mondial officiel — Personne la plus formidable',
      result3Snippet: "Le Guinness World Records certifie officiellement qu'aucune méthode connue ne permet de mesurer l'étendue totale de sa gentillesse.",
      text2: 'On a cherché partout.',
      text3: 'Des milliards de résultats.',
      text4: "Et le premier résultat, c'était",
      text4Adjective: 'toi',
      text5Entry: 'Parce que,',
      text5Content: 'Tu es unique',
      smiley: ':)',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'Le meilleur reste à venir 🚀',
      outroText: "On espère que tu as aimé.",
      replayText: 'Revoir ↺',
      outroSmiley: ':)',
    },
    defaultStyle: { primaryColor: '#a18cd1', accentColor: '#fbc2eb', fontFamily: 'Work Sans', fontSize: 'medium', theme: 'dark' },
  },

  /* ── forever (Hommage) ──────────────────────────────────── */
  {
    name: 'forever',
    label: 'Hommage',
    description: 'Sobre, digne, intemporel. Cadres dorés et typographie élégante pour créer un souvenir mémorable.',
    price: 1000,
    creditsRequired: 2,
    emoji: '✦',
    gradient: 'linear-gradient(135deg,#1e3a5f,#2c2218)',
    highlights: ['Cadres & typographie classiques', 'Citation ou poème central', 'Galerie chronologique', 'Lien privé non-indexé'],
    tags: ['hommage', 'mémorial'],
    sortOrder: 6,
    active: true,
    featured: false,
    ///Merde c'est un template d'amour
    fields: [
      { key: 'name',         label: 'Prénom | Nom',      type: 'text',     section: 'Intro',  placeholder: 'Grand-père Jean',     required: true },
      { key: 'greetingText', label: "Message d'introduction",      type: 'textarea', section: 'Intro',  placeholder: 'Nous te dédions cet hommage...'      },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)', type: 'url',      section: 'Music',  placeholder: 'https://... .mp3'                    },
      { key: 'musicStartTime',label: 'Démarrer à (secondes)',      type: 'starttime',section: 'Music'                                                      },
      { key: 'trackTitle',   label: 'Titre de la musique',         type: 'text',     section: 'Music',  placeholder: 'Ma mélodie'                          },
      { key: 'trackArtist',  label: 'Artiste',                     type: 'text',     section: 'Music'                                                      },
      { key: 'quote',        label: 'Citation ou poème',           type: 'textarea', section: 'Story',  placeholder: 'Une phrase qui lui ressemble...'      },
      { key: 'tribute',      label: 'Message Principal',           type: 'textarea', section: 'Story',  placeholder: 'Des mots du fond du cœur...', required: true },
      { key: 'wishHeading',  label: 'Titre de clôture',            type: 'text',     section: 'Wishes', placeholder: 'Pour toujours dans nos mémoires'      },
      { key: 'wishText',     label: 'Sous-titre de clôture',       type: 'text',     section: 'Wishes', placeholder: '✦'                                   },
      { key: 'outroText',    label: 'Message de fin',              type: 'text',     section: 'Outro',  placeholder: 'Toujours dans nos cœurs.'             },
    ],
    defaultData: {
      name: 'Sally',
      greetingText: 'Hey',
      quote: 'Une pensée pour toi !',
      tribute: '',
      wishHeading: ' ',
      wishText: '',
      outroText: 'Gros Bisous !',
    },
    defaultStyle: { primaryColor: '#c9a84c', accentColor: '#ffffff', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'dark' },
  },

  /* ── collective-family ──────────────────────────────────── */
  {
    name: 'collective-family',
    label: 'Collectif Famille',
    description: "Chaque proche ajoute son message et sa photo — un souvenir partagé jusqu'à 50 contributeurs.",
    price: 2000,
    creditsRequired: 4,
    emoji: '👨‍👩‍👧‍👦',
    gradient: 'linear-gradient(135deg,#f093fb,#f5576c)',
    highlights: ["Jusqu'à 50 contributeurs", 'Messages texte, audio ou vidéo', 'Galerie photos partagée', 'Album téléchargeable PDF'],
    tags: ['collectif', 'famille'],
    sortOrder: 4,
    active: true,
    featured: false,
    fields: [
      { key: 'name',         label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',    placeholder: 'Ama',                                        required: true },
      { key: 'greeting',     label: "Message d'accueil",          type: 'text',      section: 'Intro',    placeholder: 'Coucou'                                                        },
      { key: 'greetingText', label: 'Note personnelle',           type: 'text',      section: 'Intro',    placeholder: "On t'aime tellement !"                                         },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                              },
      { key: 'musicStartTime',label: 'Démarrer à (secondes)',     type: 'starttime', section: 'Musique'                                                                                },
      { key: 'trackTitle',   label: 'Titre de la musique',        type: 'text',      section: 'Musique',  placeholder: 'Notre chanson'                                                 },
      { key: 'trackArtist',  label: 'Artiste',                    type: 'text',      section: 'Musique',  placeholder: 'Artiste préféré'                                               },
      { key: 'musicHint',    label: 'Indication musique',         type: 'text',      section: 'Musique',  placeholder: "C'est mieux avec de la musique 🎶"                             },
      { key: 'groupName',    label: 'Nom du groupe / famille',    type: 'text',      section: 'Message',  placeholder: 'La famille',                         required: true            },
      { key: 'groupMessage', label: 'Message du groupe',          type: 'textarea',  section: 'Message',  placeholder: "On s'est réunis pour te dire quelque chose…"                  },
      { key: 'groupEmojis',  label: 'Emojis du groupe',           type: 'text',      section: 'Message',  placeholder: '🥰 🎂 🎊'                                                     },
      { key: 'text2',        label: "Phrase d'histoire 1",        type: 'text',      section: 'Histoire', placeholder: 'On a cherché les mots.'                                        },
      { key: 'text3',        label: "Phrase d'histoire 2",        type: 'text',      section: 'Histoire', placeholder: 'On en a trouvé beaucoup.'                                      },
      { key: 'text4',        label: "Phrase d'histoire 3",        type: 'text',      section: 'Histoire', placeholder: 'Mais surtout, on voulait dire'                                 },
      { key: 'text4Adjective',label: "Mot clé de l'histoire",     type: 'text',      section: 'Histoire', placeholder: 'merci'                                                         },
      { key: 'text5Entry',   label: 'Intro phrase finale',        type: 'text',      section: 'Histoire', placeholder: 'Parce que,'                                                    },
      { key: 'text5Content', label: 'Phrase finale',              type: 'text',      section: 'Histoire', placeholder: 'Tu es irremplaçable'                                           },
      { key: 'smiley',       label: 'Emoji principal',            type: 'text',      section: 'Histoire', placeholder: '🥰'                                                            },
      { key: 'wishHeading',  label: 'Titre du vœu',               type: 'text',      section: 'Vœu',      placeholder: 'Joyeux Anniversaire !',              required: true            },
      { key: 'wishText',     label: 'Sous-titre du vœu',          type: 'text',      section: 'Vœu',      placeholder: 'De toute la famille avec amour 💖'                             },
      { key: 'carouselTitle',label: 'Titre du carrousel vœux',    type: 'text',      section: 'Vœu',      placeholder: "Ce qu'ils ont voulu te dire 💌"                                },
      { key: 'outroText',    label: 'Message de fin',             type: 'text',      section: 'Outro',    placeholder: 'Reviens nous dire si tu as aimé.'                              },
      { key: 'replayText',   label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',    placeholder: 'Clique pour revoir ↺'                                          },
      { key: 'outroSmiley',  label: 'Emoji de fin',               type: 'text',      section: 'Outro',    placeholder: '🥰'                                                            },
    ],
    defaultData: {
      greeting: 'Coucou',
      name: 'Sally',
      greetingText: "Notre meuf adorée !",
      musicHint: "C'est mieux avec de la musique 🎶",
      trackTitle: 'Notre chanson',
      trackArtist: 'Artiste préféré',
      groupName: 'Tes meilleurs potes',
      groupMessage: "Today is your day !",
      groupEmojis: '🥰 🎂 🎊',
      text2: 'On a cherché les mots.',
      text3: 'On en a trouvé beaucoup.',
      text4: 'Mais surtout, on voulait te dire',
      text4Adjective: 'merci',
      text5Entry: 'Parce que,',
      text5Content: 'Tu es unique !',
      smiley: ':)',
      wishHeading: 'Happy Birthday !',
      wishText: 'From our hearts 💖 Be happy !',
      carouselTitle: "Les mots de chacun",
      outroText: 'On espère que tu as kiffé.',
      replayText: 'Revoir ↺',
      outroSmiley: ':)',
    },
    defaultStyle: { primaryColor: '#f093fb', accentColor: '#f5576c', fontFamily: 'Work Sans', fontSize: 'medium', theme: 'light' },
  },

  /* ── collective-pro ─────────────────────────────────────── */
  {
    name: 'collective-pro',
    label: 'Collectif Pro',
    description: "Pour célébrer vos équipes avec classe : branding entreprise, signatures et export HD.",
    price: 2000,
    creditsRequired: 4,
    emoji: '🏢',
    gradient: 'linear-gradient(135deg,#1e3a5f,#0f1e30)',
    highlights: ["Logo & couleurs entreprise", "Sous-domaine personnalisé", "Contributions illimitées", "Statistiques d'engagement"],
    tags: ['collectif', 'entreprise', 'pro'],
    sortOrder: 5,
    active: true,
    featured: false,
    fields: [
      { key: 'name',         label: 'Prénom / Nom du destinataire',  type: 'text',      section: 'Intro',    placeholder: 'Alexandre',                                   required: true },
      { key: 'greeting',     label: "Formule d'appel",               type: 'text',      section: 'Intro',    placeholder: 'Cher'                                                          },
      { key: 'greetingText', label: "Phrase d'introduction",         type: 'text',      section: 'Intro',    placeholder: 'Nous tenions à marquer ce moment.'                             },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)',    type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                              },
      { key: 'musicStartTime',label: 'Démarrer à (secondes)',        type: 'starttime', section: 'Musique'                                                                                },
      { key: 'trackTitle',   label: 'Titre de la musique',           type: 'text',      section: 'Musique',  placeholder: 'Un morceau pour vous'                                          },
      { key: 'trackArtist',  label: 'Artiste',                       type: 'text',      section: 'Musique',  placeholder: "Sélection de l'équipe"                                         },
      { key: 'musicHint',    label: 'Indication musique',            type: 'text',      section: 'Musique',  placeholder: 'Prenez un moment pour écouter 🎵'                              },
      { key: 'groupName',    label: "Nom de l'équipe / département", type: 'text',      section: 'Message',  placeholder: "L'équipe Marketing",                 required: true            },
      { key: 'groupMessage', label: "Message de l'équipe",           type: 'textarea',  section: 'Message',  placeholder: "Nous nous sommes réunis pour vous adresser quelques mots…"    },
      { key: 'text2',        label: 'Phrase de transition 1',        type: 'text',      section: 'Histoire', placeholder: 'Nous avons cherché les mots justes.'                           },
      { key: 'text3',        label: 'Phrase de transition 2',        type: 'text',      section: 'Histoire', placeholder: 'Nous en avons trouvé beaucoup.'                               },
      { key: 'text4',        label: 'Phrase de transition 3',        type: 'text',      section: 'Histoire', placeholder: "Mais ce qui compte vraiment, c'est"                           },
      { key: 'text4Adjective',label: 'Mot clé',                      type: 'text',      section: 'Histoire', placeholder: 'vous'                                                          },
      { key: 'text5Entry',   label: 'Intro phrase finale',           type: 'text',      section: 'Histoire', placeholder: 'Car,'                                                          },
      { key: 'text5Content', label: 'Phrase finale',                 type: 'text',      section: 'Histoire', placeholder: 'Votre présence compte'                                         },
      { key: 'smiley',       label: 'Ponctuation finale',            type: 'text',      section: 'Histoire', placeholder: '.'                                                             },
      { key: 'wishHeading',  label: 'Titre du vœu',                  type: 'text',      section: 'Vœu',      placeholder: 'Félicitations',                      required: true            },
      { key: 'wishText',     label: 'Sous-titre du vœu',             type: 'text',      section: 'Vœu',      placeholder: 'Avec toute notre considération'                                },
      { key: 'carouselTitle',label: 'Titre du carrousel messages',   type: 'text',      section: 'Vœu',      placeholder: "Ce que l'équipe a voulu vous dire"                             },
      { key: 'outroText',    label: 'Message de clôture',            type: 'text',      section: 'Outro',    placeholder: 'Nous espérons que ce moment vous a touché.'                   },
      { key: 'replayText',   label: 'Texte du bouton revoir',        type: 'text',      section: 'Outro',    placeholder: '↺ Revoir'                                                      },
      { key: 'outroSmiley',  label: 'Symbole de fin',                type: 'text',      section: 'Outro',    placeholder: '✦'                                                             },
    ],
    defaultData: {
      greeting: 'Cher',
      name: 'Prénom Nom',
      greetingText: 'Nous tenions à marquer ce moment.',
      musicHint: 'Prenez un moment pour écouter 🎵',
      trackTitle: 'Votre chansaon préférée',
      trackArtist: "Sélection de l'équipe",
      groupName: "L'équipe",
      groupMessage: "En ce jour magnifique..",
      text2: 'Nous avons cherché les mots justes.',
      text3: 'Nous en avons trouvé beaucoup.',
      text4: "Mais ce qui compte vraiment, c'est",
      text4Adjective: 'vous',
      text5Entry: 'Car,',
      text5Content: 'Votre présence compte',
      smiley: ':)',
      wishHeading: 'Joyeux Anniversaire',
      wishText: 'Avec toute notre considération !',
      carouselTitle: "Les mots de chacun",
      outroText: 'On espère que ça a vous a plu !',
      replayText: '↺ Revoir',
      outroSmiley: '✦',
    },
    defaultStyle: { primaryColor: '#c9a84c', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'dark' },
  },

  /* ── sanctuary ──────────────────────────────────────────── */
  {
    name: 'sanctuary',
    label: 'Sanctuary',
    description: 'Un cadre serein et minimaliste pour les moments qui comptent vraiment.',
    price: 6000,
    creditsRequired: 12,
    emoji: '🌸',
    gradient: 'linear-gradient(135deg,#f5f0e8,#e8d5c4)',
    highlights: ["Mise en page apaisante", "Photos & texte animés", "Musique d'ambiance", "Lien privé"],
    tags: ['élégant', 'serein', 'minimaliste'],
    sortOrder: 7,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',  placeholder: 'Élise',                           required: true },
      { key: 'greeting',       label: "Message d'accueil",          type: 'text',      section: 'Intro',  placeholder: 'Chère'                                           },
      { key: 'greetingText',   label: "Note d'introduction",        type: 'textarea',  section: 'Intro',  placeholder: 'Ce moment est pour toi.'                         },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Music',  placeholder: 'https://... .mp3'                                },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',      type: 'starttime', section: 'Music'                                                                  },
      { key: 'trackTitle',     label: 'Titre de la musique',        type: 'text',      section: 'Music'                                                                  },
      { key: 'trackArtist',    label: 'Artiste',                    type: 'text',      section: 'Music'                                                                  },
      { key: 'text2',          label: 'Première phrase',            type: 'text',      section: 'Story',  placeholder: 'Il y a des moments...'                           },
      { key: 'text3',          label: 'Deuxième phrase',            type: 'text',      section: 'Story',  placeholder: 'Qui méritent d\'être célébrés.'                  },
      { key: 'text4Adjective', label: 'Mot clé central',            type: 'text',      section: 'Story',  placeholder: 'précieux'                                        },
      { key: 'wishHeading',    label: 'Titre du vœu',               type: 'text',      section: 'Wishes', placeholder: 'Pour toi 💛',                    required: true },
      { key: 'wishText',       label: 'Sous-titre du vœu',          type: 'text',      section: 'Wishes', placeholder: 'Avec toute notre tendresse'                      },
      { key: 'outroText',      label: 'Message de fin',             type: 'text',      section: 'Outro',  placeholder: 'Que ce moment reste gravé.'                      },
      { key: 'replayText',     label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',  placeholder: 'Revoir ↺'                                        },
    ],
    defaultData: {
      greeting: 'Chère',
      name: 'Sally',
      greetingText: 'Ce moment est pour toi.',
      text2: 'Il y a des moments...',
      text3: "Qui méritent d'être célébrés.",
      text4Adjective: 'précieux',
      wishHeading: 'Pour toi 💛',
      wishText: 'Avec toute notre tendresse',
      outroText: 'Que ce moment reste gravé.',
      replayText: 'Revoir ↺',
    },
    defaultStyle: { primaryColor: '#a8856a', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'light' },
  },

  /* ── notre-film ─────────────────────────────────────────── */
  {
    name: 'notre-film',
    label: 'Notre Film',
    description: 'Un slideshow cinématique pour raconter votre histoire en images.',
    price: 1500,
    creditsRequired: 3,
    emoji: '🎬',
    gradient: 'linear-gradient(135deg,#1a1410,#3d2b1f)',
    highlights: ['Transitions cinématiques', 'Photos & vidéos mixées', 'Bande-son personnalisée', 'Format 16:9 HD'],
    tags: ['cinématique', 'vidéo', 'premium'],
    sortOrder: 8,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',  placeholder: 'Emma',                            required: true },
      { key: 'greeting',       label: 'Dédicace du film',           type: 'text',      section: 'Intro',  placeholder: 'Ce film est pour toi.'                           },
      { key: 'musicSrc',       label: 'Bande-son (URL .mp3)',       type: 'url',       section: 'Music',  placeholder: 'https://... .mp3'                                },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',      type: 'starttime', section: 'Music'                                                                  },
      { key: 'albumArt',       label: "Pochette / Image d'ambiance",type: 'url',       section: 'Music',  placeholder: 'https://... .jpg'                                },
      { key: 'trackTitle',     label: 'Titre de la bande-son',      type: 'text',      section: 'Music'                                                                  },
      { key: 'trackArtist',    label: 'Compositeur / Artiste',      type: 'text',      section: 'Music'                                                                  },
      { key: 'text2',          label: 'Première scène (texte)',      type: 'text',      section: 'Story',  placeholder: 'Il était une fois...'                            },
      { key: 'text3',          label: 'Deuxième scène (texte)',      type: 'text',      section: 'Story',  placeholder: 'Une personne exceptionnelle.'                    },
      { key: 'text4Adjective', label: 'Mot-clé du film',            type: 'text',      section: 'Story',  placeholder: 'extraordinaire'                                  },
      { key: 'text5Content',   label: 'Phrase titre du film',       type: 'text',      section: 'Story',  placeholder: 'Notre film, notre histoire.'                     },
      { key: 'wishHeading',    label: 'Titre du générique',         type: 'text',      section: 'Wishes', placeholder: 'Joyeux Anniversaire !',           required: true },
      { key: 'wishText',       label: 'Sous-titre du générique',    type: 'text',      section: 'Wishes', placeholder: 'Avec tout notre amour 🎬'                        },
      { key: 'outroText',      label: 'Générique de fin',           type: 'text',      section: 'Outro',  placeholder: 'Fin.'                                            },
      { key: 'replayText',     label: 'Bouton revoir',              type: 'text',      section: 'Outro',  placeholder: '↺ Revoir le film'                                },
    ],
    defaultData: {
      greeting: 'Pour toi,',
      name: 'Prénom',
      text2: 'Il était une fois...',
      text3: 'Une personne exceptionnelle.',
      text4Adjective: 'extraordinaire',
      text5Content: 'Notre film, notre histoire.',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'From my heart',
      outroText: 'Fin.',
      replayText: '↺ Revoir',
    },
    defaultStyle: { primaryColor: '#c9a84c', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'dark' },
  },
];

/* ─────────────────────────────────────────────────────────────
   Seed runner
───────────────────────────────────────────────────────────── */
async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✓ Connecté à MongoDB\n');

  for (const tpl of TEMPLATES) {
    const { name, ...rest } = tpl;
    await Template.findOneAndUpdate(
      { name },
      { name, ...rest },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`✓ Template "${name}" mis à jour (${tpl.fields.length} champs)`);
  }

  console.log('\n──────────────────────────────────────');
  console.log(`${TEMPLATES.length} templates mis à jour avec les labels en français.`);
  console.log('──────────────────────────────────────\n');

  await mongoose.disconnect();
  console.log('Terminé.');
}

seed().catch(e => { console.error(e); process.exit(1); });
