/**
 * Seed corrector  fields en français pour tous les templates
 * Usage : node server/seeds/seedTemplates.js
 *   ou  : npm run seed:templates  (depuis server/)
 *
 * Ce script upsert chaque template avec :
 *   - labels de champs en français
 *   - données par défaut (defaultData) en français
 *   - métadonnées (label, description, highlights, etc.)
 * Il ne supprime PAS les vœux ni les publications existantes.
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Template = require('../models/Template');

/* ─────────────────────────────────────────────────────────────
   Définition des templates
───────────────────────────────────────────────────────────── */
const TEMPLATES = [

  /* ── birthday ───────────────────────────────────────────── */
  {
    name: 'birthday',
    label: 'Joyeux Anniversaire',
    description: "Animation complète avec photos, musique et vœux personnalisés. L'incontournable.",
    price: 1000,
    creditsRequired: 2,
    emoji: '🎂',
    gradient: 'linear-gradient(135deg,#ffb4d1,#f7d59e)',
    highlights: ['Musique personnalisée (MP3)', '3 styles de typographie', 'Lien privé + QR code'],
    tags: ['anniversaire', 'classique'],
    sortOrder: 1,
    active: true,
    featured: true,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',    type: 'text',      section: 'Intro',     placeholder: 'Sally',                                    required: true  },
      { key: 'greeting',       label: "Message d'accueil",         type: 'text',      section: 'Intro',     placeholder: 'Coucou'                                                         },
      { key: 'greetingText',   label: 'Note personnelle',          type: 'text',      section: 'Intro',     placeholder: "Ma star du jour !"                           },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)',type: 'url',       section: 'Musique',   placeholder: 'https://... .mp3'                                               },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',     type: 'starttime', section: 'Musique'                                                                                   },
      { key: 'albumArt',       label: "Pochette de l'album (URL)", type: 'url',       section: 'Musique',   placeholder: 'https://... .jpg'                                               },
      { key: 'trackTitle',     label: 'Titre de la musique',       type: 'text',      section: 'Musique',   placeholder: 'Happy Birthday'                                                 },
      { key: 'trackArtist',    label: 'Artiste',                   type: 'text',      section: 'Musique',   placeholder: 'Naza'                                                  },
      { key: 'musicHint',      label: 'Indication musique',        type: 'text',      section: 'Musique',   placeholder: "C'est mieux avec de la musique 🎶"                              },
      { key: 'text1',          label: "Accroche principale",       type: 'text',      section: 'Message',   placeholder: "C'est ton anniversaire !!! 🎉"                                  },
      { key: 'waName',         label: 'Nom du contact WhatsApp',  type: 'text',      section: 'Message',   placeholder: 'Prénom'                                                                 },
      { key: 'textInChatBox',  label: 'Message WhatsApp',          type: 'textarea',  section: 'Message',   placeholder: "Joyeux anniversaire !!! 🎉 Je te souhaite le meileur.. blah blah blah !" },
      { key: 'text2',          label: "Phrase d'histoire 1",       type: 'text',      section: 'Histoire',  placeholder: "C'est ce que j'allais t'écrire.."                                         },
      { key: 'text3',          label: "Phrase d'histoire 2",       type: 'text',      section: 'Histoire',  placeholder: 'Et puis je me suis arrêté.'                                       },
      { key: 'text4',          label: "Phrase d'histoire 3",       type: 'text',      section: 'Histoire',  placeholder: "J'ai réalisé que je voulais faire un truc "                                  },
      { key: 'text4Adjective', label: "Mot clé de l'histoire",     type: 'text',      section: 'Histoire',  placeholder: 'Unique'                                                          },
      { key: 'text5Entry',     label: 'Intro phrase finale',       type: 'text',      section: 'Histoire',  placeholder: 'Parce que,'                                                     },
      { key: 'text5Content',   label: 'Phrase finale',             type: 'text',      section: 'Histoire',  placeholder: 'Tu es spéciale'                                            },
      { key: 'smiley',         label: 'Emoji principal',           type: 'text',      section: 'Histoire',  placeholder: ':)'                                                             },
      { key: 'bigTextPart1', label: 'Première Lettre', type: 'text', section: 'Histoire', placeholder: 'S' },
      { key: 'bigTextPart2', label: 'Deuxième Lettre', type: 'text', section: 'Histoire', placeholder: 'O' },
      { key: 'imagePath',      label: 'Photo principale',          type: 'url',       section: 'Célébration', placeholder: 'https://... .jpg'                                           },
      { key: 'photo1',         label: 'Photo gauche',              type: 'url',       section: 'Célébration', placeholder: 'https://... .jpg'                                           },
      { key: 'photo2',         label: 'Photo droite',              type: 'url',       section: 'Célébration', placeholder: 'https://... .jpg'                                           },
      { key: 'imageLayout',    label: 'Disposition photos',        type: 'layout',    section: 'Célébration',
        options: [
          { value: 'grid',      label: 'Grille',  icon: '▦' },
          { value: 'stack',     label: 'Pile',    icon: '⧉' },
          { value: 'spotlight', label: 'Focus',   icon: '◎' },
          { value: 'row',       label: 'Rangée',  icon: '▬' },
        ]
      },
      { key: 'wishHeading',    label: 'Titre du vœu',              type: 'text',      section: 'Vœu',       placeholder: 'Joyeux Anniversaire !',                     required: true      },
      { key: 'wishText',       label: 'Sous-titre du vœu',         type: 'text',      section: 'Vœu',       placeholder: 'Bel âge à toi !'                                       },
      { key: 'wish1',          label: 'Vœu 1',                     type: 'textarea',  section: 'Vœux',      placeholder: 'Ton premier vœu…'                                                     },
      { key: 'wish2',          label: 'Vœu 2',                     type: 'textarea',  section: 'Vœux',      placeholder: 'Ton deuxième vœu…'                                                    },
      { key: 'wish3',          label: 'Vœu 3',                     type: 'textarea',  section: 'Vœux',      placeholder: 'Ton troisième vœu…'                                                   },
      { key: 'outroText',      label: 'Message de fin',            type: 'text',      section: 'Outro',     placeholder: "Bon, J'espère que tu as kiffé !"                               },
      { key: 'replayText',     label: 'Texte du bouton revoir',    type: 'text',      section: 'Outro',     placeholder: 'Clique ici pour revoir ↺'                                           },
      { key: 'outroSmiley',    label: 'Emoji de fin',              type: 'text',      section: 'Outro',     placeholder: ':)'                                                             },
    ],
    defaultData: {
      greeting: 'Coucou',
      name: 'Sally',
      greetingText: "Ma star du jour !",
      musicHint: "C'est mieux avec de la musique 🎶",
      text1: "C'est ton anniversaire !!! 🎉",
      waName: 'Sally',
      waAvatar: 'S',
      textInChatBox: "Joyeux anniversaire !!! 🎉 Je te souhaite le meileur.. blah blah blah !!",
      text2: "C'est ce que j'allais t'écrire..",
      text3: 'Et puis je me suis arrêté.',
      text4: "J'ai réalisé que je voulais faire un truc ",
      text4Adjective: 'Unique',
      text5Entry: 'Parce que,',
      text5Content: 'Tu es Spéciale',
      smiley: ':)',
      bigTextPart1: 'S', bigTextPart2: 'O',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'Bel âge à toi !',
      wish1: 'Que cette nouvelle année de ta vie soit remplie de joie, de lumière et de toutes ces petites choses qui font sourire.',
      wish2: 'Tu mérites tout le bonheur du monde, et je souhaite que chaque journée t\'apporte quelque chose de beau.',
      wish3: 'Joyeux anniversaire du fond du cœur. 🎂✨',
      outroText: "J'espère que tu as kiffé !",
      replayText: 'Revoir ↺',
      outroSmiley: ':)',
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* ── wall-of-wishes ─────────────────────────────────────── */
  {
    name: 'wall-of-wishes',
    label: 'Mur de vœux',
    description: "Un mur interactif où chacun colle son message  comme des post-its numériques.",
    price: 5000,
    creditsRequired: 10,
    emoji: '💌',
    gradient: 'linear-gradient(135deg,#fdf6c3,#fce4ec,#ede7f6)',
    highlights: ["Jusqu'à 30 contributeurs", 'Modération avant publication', '6 couleurs de post-it', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif'],
    sortOrder: 2,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'Prénom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Partagez ce lien  laissez votre message ici.' },
    ],
    defaultData: {
      titleName: 'Prénom',
      subtitle: 'Partagez ce lien  chacun peut laisser son mot sur ce mur.',
    },
    defaultStyle: { primaryColor: '#E11D48', accentColor: '#E11D48', fontFamily: 'Plus Jakarta Sans', fontSize: 'medium', theme: 'light' },
  },

  /* ── wall-of-wishes-modern ──────────────────────────────── */
  {
    name: 'wall-of-wishes-modern',
    label: 'Mur Moderne',
    description: "Mur de vœux glassmorphisme sur fond dégradé lavande-rose. Cards sociales élégantes avec avatar et rôle.",
    price: 5000,
    creditsRequired: 10,
    emoji: '💬',
    gradient: 'linear-gradient(135deg,#ccc0f5,#e8b0d8,#f5a8be)',
    highlights: ['Design glassmorphisme', 'Champ relation/rôle', 'Barre de cagnotte intégrée', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif', 'moderne'],
    sortOrder: 9,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'Prénom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'eyebrow',   label: 'Badge en haut du mur',   type: 'text',     section: 'Mur', placeholder: '✦ Mur de vœux' },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Partagez ce lien  laissez votre message ici.' },
    ],
    defaultData: {
      titleName: 'Prénom',
      eyebrow: '✦ Mur de vœux',
      subtitle: 'Partagez ce lien  chacun peut laisser son mot sur ce mur.',
    },
    defaultStyle: { primaryColor: '#7C5CC9', accentColor: '#7C5CC9', fontFamily: 'Plus Jakarta Sans', fontSize: 'medium', theme: 'light' },
  },

  /* ── wall-of-wishes-space ────────────────────────────────── */
  {
    name: 'wall-of-wishes-space',
    label: 'Mur Spatial',
    description: "Canvas infini de vœux style Polaroid sur fond corail. Pan, zoom et vue détail au clic.",
    price: 5000,
    creditsRequired: 10,
    emoji: '🚀',
    gradient: 'linear-gradient(135deg,#ff8060,#ff4878,#d83070)',
    highlights: ['Canvas infini pan + zoom', 'Cartes Polaroid éparpillées', 'Vue détail au clic', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif', 'spatial'],
    sortOrder: 10,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'Prénom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'eyebrow',   label: 'Badge en haut du mur',   type: 'text',     section: 'Mur', placeholder: '✦ Mur de vœux' },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Glisse pour explorer · Clique pour lire.' },
    ],
    defaultData: {
      titleName: 'Prénom',
      eyebrow: '✦ Mur de vœux',
      subtitle: 'Glisse pour explorer · Clique sur une carte pour lire le vœu.',
    },
    defaultStyle: { primaryColor: '#ff4878', accentColor: '#ff8060', fontFamily: 'Inter', fontSize: 'medium', theme: 'light' },
  },

  /* ── special ────────────────────────────────────────────── */
  {
    name: 'special',
    label: 'Vœu Spécial',
    description: "Montrez on a une personne à quel point elle est unique !",
    price: 1000,
    creditsRequired: 2,
    emoji: '✦',
    gradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
    highlights: ['Thème sur-mesure', 'Particules & transitions premium', 'Export vidéo MP4 HD', 'Photos illimitées'],
    tags: ['premium', 'spécial'],
    sortOrder: 3,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',    placeholder: 'Sally',                                                     required: true },
      { key: 'greeting',       label: "Message d'accueil",          type: 'text',      section: 'Intro',    placeholder: 'Coucou'                                                                         },
      { key: 'greetingText',   label: 'Note personnelle',           type: 'text',      section: 'Intro',    placeholder: "On a mené notre petite enquête.."                                                 },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                                               },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',      type: 'starttime', section: 'Musique'                                                                                                  },
      { key: 'albumArt',       label: "Pochette de l'album (URL)",  type: 'url',       section: 'Musique',  placeholder: 'https://... .jpg'                                                               },
      { key: 'trackTitle',     label: 'Titre de la musique',        type: 'text',      section: 'Musique',  placeholder: 'Gold'                                                                           },
      { key: 'trackArtist',    label: 'Artiste',                    type: 'text',      section: 'Musique',  placeholder: 'Spandau Ballet'                                                                 },
      { key: 'musicHint',      label: 'Indication musique',         type: 'text',      section: 'Musique',  placeholder: "C'est mieux avec de la musique 🎶"                                              },
      { key: 'text1',          label: 'Accroche avant la recherche',type: 'text',      section: 'Google',   placeholder: 'Et on a lancé une recherche… 🔍'                                                    },
      { key: 'searchQuery',    label: 'Requête Google',             type: 'text',      section: 'Google',   placeholder: 'la meilleure personne du monde'                                                    },
      { key: 'result1Title',   label: 'Titre résultat #1',          type: 'text',      section: 'Google',   placeholder: 'La personne la plus exceptionnelle recensée sur Terre'                          },
      { key: 'result1Snippet', label: 'Extrait résultat #1',        type: 'textarea',  section: 'Google',   placeholder: "Après analyse de 8 milliards de profils, les experts s'accordent…"             },
      { key: 'result1Domain',  label: 'Domaine résultat #1',        type: 'text',      section: 'Google',   placeholder: 'patrimoine-de-l-humanite.org'                                                                 },
      { key: 'result1Rating',  label: 'Note résultat #1',           type: 'text',      section: 'Google',   placeholder: "⭐ 5,0/5 · Avis validés par l'univers entier"                                                },
      { key: 'result2Title',   label: 'Titre résultat #2',          type: 'text',      section: 'Google',   placeholder: 'Définition de « Parfaite »  Dictionnaire Illustré'                                   },
      { key: 'result2Snippet', label: 'Extrait résultat #2',        type: 'textarea',  section: 'Google',   placeholder: "L'Académie a récemment mis à jour sa définition du mot \"parfaite\" pour y intégrer directement une photo d'elle."    },
      { key: 'result3Title',   label: 'Titre résultat #3',          type: 'text',      section: 'Google',   placeholder: 'Guinness World Records  Cœur en or certifié'                          },
      { key: 'result3Snippet', label: 'Extrait résultat #3',        type: 'textarea',  section: 'Google',   placeholder: "Record officiellement validé : aucune technologie actuelle ne permet de mesurer l'étendue totale de sa bienveillance."                             },
      { key: 'text2',          label: "Phrase de transition 1",     type: 'text',      section: 'Histoire', placeholder: 'On a fouillé le web entier.'                                                          },
      { key: 'text3',          label: "Phrase de transition 2",     type: 'text',      section: 'Histoire', placeholder: 'Passé au crible des milliards de résultats.'                                                    },
      { key: 'text4',          label: "Phrase de transition 3",     type: 'text',      section: 'Histoire', placeholder: "Mais l'évidence était là, c'était"                                               },
      { key: 'text4Adjective', label: 'Adjectif clé',               type: 'text',      section: 'Histoire', placeholder: 'TOI'                                                                            },
      { key: 'text5Entry',     label: 'Intro phrase finale',        type: 'text',      section: 'Histoire', placeholder: 'Parce que,'                                                                     },
      { key: 'text5Content',   label: 'Phrase finale',              type: 'text',      section: 'Histoire', placeholder: 'Tu es unique'                                                                   },
      { key: 'bigTextPart1', label: 'Première Lettre', type: 'text', section: 'Histoire', placeholder: 'S' },
      { key: 'bigTextPart2', label: 'Deuxième Lettre', type: 'text', section: 'Histoire', placeholder: 'O' },
      { key: 'smiley',         label: 'Emoji principal',            type: 'text',      section: 'Histoire', placeholder: ':)'                                                                             },
      { key: 'wishHeading',    label: 'Titre du vœu',               type: 'text',      section: 'Vœu',      placeholder: 'Joyeux Anniversaire !',                             required: true             },
      { key: 'wishText',       label: 'Sous-titre du vœu',          type: 'text',      section: 'Vœu',      placeholder: 'Profite à fond, le meilleur reste à venir 🚀'                                                   },
      { key: 'outroText',      label: 'Message de fin',             type: 'text',      section: 'Outro',    placeholder: "On espère que cette petite surprise t'a fait sourire !"                                                      },
      { key: 'replayText',     label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',    placeholder: "Revoir ↺"                                                                       },
      { key: 'outroSmiley',    label: 'Emoji de fin',               type: 'text',      section: 'Outro',    placeholder: '🎉'                                                                             },
    ],
    defaultData: {
      "greeting": "Coucou",
      "name": "Sally",
      "greetingText": "On a mené notre petite enquête...",
      "musicHint": "C'est mieux avec le son activé 🎶",
      "text1": "Et on a lancé une recherche… 🔍",
      "trackTitle": "Happy Birthday",
      "trackArtist": "Naza",
      "searchQuery": "la meilleure personne au monde",
      "result1Title": "La personne la plus exceptionnelle recensée sur Terre",
      "result1Snippet": "Après l'analyse approfondie de 8 milliards de profils, les experts s'accordent sur un résultat incontestable.",
      "result1Domain": "patrimoine-de-l-humanite.org",
      "result1Rating": "⭐ 5,0/5 · Avis validés par l'univers entier",
      "result2Title": "Définition de « Parfaite »  Dictionnaire Illustré",
      "result2Snippet": "L'Académie a récemment mis à jour sa définition du mot \"parfaite\" pour y intégrer directement une photo d'elle.",
      "result3Title": "Guinness World Records  Cœur en or certifié",
      "result3Snippet": "Record officiellement validé : aucune technologie actuelle ne permet de mesurer l'étendue totale de sa bienveillance.",
      "text2": "On a fouillé le web entier.",
      "text3": "Passé au crible des milliards de résultats.",
      "text4": "Mais l'évidence était là, c'était",
      "text4Adjective": "TOI",
      "text5Entry": "Tout simplement parce que,",
      "text5Content": "Tu es unique",
      "smiley": ":)",
      "wishHeading": "Joyeux Anniversaire !",
      "wishText": "Profite à fond, le meilleur reste à venir 🚀",
      "outroText": "On espère que cette petite surprise t'a fait sourire !",
      "replayText": "Revoir l'animation ↺",
      "outroSmiley": ":)"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* ── forever (Hommage) ──────────────────────────────────── */
  {
    name: 'forever',
    label: 'Hommage',
    description: 'Sobre, digne, intemporel. Cadres dorés et typographie élégante pour créer un souvenir mémorable.',
    price: 1000,
    creditsRequired: 2,
    emoji: '✦',
    gradient: 'linear-gradient(135deg,#1e3a5f,#2c2218)',
    highlights: ['Cadres & typographie classiques', 'Citation ou poème central', 'Galerie chronologique', 'Lien privé non-indexé'],
    tags: ['hommage', 'mémorial'],
    sortOrder: 6,
    active: true,
    featured: false,
    //
    fields: [
      { key: 'name',         label: 'Prénom | Nom',      type: 'text',     section: 'Intro',  placeholder: "Sally",     required: true },
      { key: 'greeting',     label: '', type: 'text', section: 'Intro', placeholder: "Hey"},
      { key: 'greetingText', label: "Salutation", type: 'text', section: 'Intro', }
    ],
    defaultData: {
      "greeting": "hey,",
      "name": "Sally",
      "greetingText": "Hey",
      "countdownLabel": "Ensemble depuis",
      "keyNumber": "∞",
      "countdownUnit": "jours",
      "countdownSince": "depuis le premier jour",
      "imagePath": "",
      "photoCaption": "Toujours aussi belle.",
      "photoSub": "à chaque regard",
      "senderName": "de toi qui t'aime",
      "outroText": "Gros Bisous !",
      "replayText": "Recommencer"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* ── collective-family ──────────────────────────────────── */
  {
    name: 'collective-family',
    label: 'Collectif Famille',
    description: "Chaque proche ajoute son message et sa photo  un souvenir partagé jusqu'à 50 contributeurs.",
    price: 2000,
    creditsRequired: 4,
    emoji: '👨‍👩‍👧‍👦',
    gradient: 'linear-gradient(135deg,#f093fb,#f5576c)',
    highlights: ["Jusqu'à 50 contributeurs", 'Messages texte, audio ou vidéo', 'Galerie photos partagée', 'Album téléchargeable PDF'],
    tags: ['collectif', 'famille'],
    sortOrder: 4,
    active: true,
    featured: false,
    fields: [
      { key: 'name',         label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',    placeholder: 'Sally',                                        required: true },
      { key: 'greeting',     label: "Message d'accueil",          type: 'text',      section: 'Intro',    placeholder: 'Coucou'                                                        },
      { key: 'greetingText', label: 'Note personnelle',           type: 'text',      section: 'Intro',    placeholder: "Notre star du jour !"                                         },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                              },
      { key: 'musicStartTime',label: 'Démarrer à (secondes)',     type: 'starttime', section: 'Musique'                                                                                },
      { key: 'trackTitle',   label: 'Titre de la musique',        type: 'text',      section: 'Musique',  placeholder: 'Notre hymne'                                                 },
      { key: 'trackArtist',  label: 'Artiste',                    type: 'text',      section: 'Musique',  placeholder: 'Team Paiya'                                               },
      { key: 'musicHint',    label: 'Indication musique',         type: 'text',      section: 'Musique',  placeholder: "Mets le son, l'ambiance est meilleure 🎶"                             },
      { key: 'groupName',    label: 'Nom du groupe / famille',    type: 'text',      section: 'Message',  placeholder: 'Ta team de choc',                         required: true            },
      { key: 'groupMessage', label: 'Message du groupe',          type: 'textarea',  section: 'Message',  placeholder: "Aujourd'hui, c'est TON moment !"                  },
      { key: 'groupEmojis',  label: 'Emojis du groupe',           type: 'text',      section: 'Message',  placeholder: '🥂 🎂 🥳'                                                     },
      { key: 'text2',        label: "Phrase d'histoire 1",        type: 'text',      section: 'Histoire', placeholder: "On a essayé d'écrire de grands discours."                                        },
      { key: 'text3',        label: "Phrase d'histoire 2",        type: 'text',      section: 'Histoire', placeholder: 'On a retourné tout le dictionnaire.'                                      },
      { key: 'text4',        label: "Phrase d'histoire 3",        type: 'text',      section: 'Histoire', placeholder: "Mais au final, le plus simple c'était de te dire"                                 },
      { key: 'text4Adjective',label: "Mot clé de l'histoire",     type: 'text',      section: 'Histoire', placeholder: 'merci'                                                         },
      { key: 'text5Entry',   label: 'Intro phrase finale',        type: 'text',      section: 'Histoire', placeholder: 'Tout simplement parce que,'                                                    },
      { key: 'text5Content', label: 'Phrase finale',              type: 'text',      section: 'Histoire', placeholder: 'Tu rends nos vies meilleures'                                           },
      { key: 'smiley',       label: 'Emoji principal',            type: 'text',      section: 'Histoire', placeholder: ':)'                                                            },
      { key: 'wishHeading',  label: 'Titre du vœu',               type: 'text',      section: 'Vœu',      placeholder: 'Joyeux Anniversaire !',              required: true            },
      { key: 'wishText',     label: 'Sous-titre du vœu',          type: 'text',      section: 'Vœu',      placeholder: 'De la part de nous tous. Ne change rien ! 💖'                             },
      { key: 'carouselTitle',label: 'Titre du carrousel vœux',    type: 'text',      section: 'Vœu',      placeholder: "Ce qu'on avait vraiment sur le cœur :"                                },
      { key: 'outroText',    label: 'Message de fin',             type: 'text',      section: 'Outro',    placeholder: "On espère que cette petite attention t'a plu."                              },
      { key: 'replayText',   label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',    placeholder: 'Se refaire la scène ↺'                                          },
      { key: 'outroSmiley',  label: 'Emoji de fin',               type: 'text',      section: 'Outro',    placeholder: ':)'                                                            },
    ],
    defaultData: {
      "greeting": "Coucou",
      "name": "Sally",
      "greetingText": "Notre star du jour !",
      "musicHint": "Mets le son, l'ambiance est meilleure 🎶",
      "trackTitle": "Notre Hymne",
      "trackArtist": "Team Paiya",
      "groupName": "Ta team de choc",
      "groupMessage": "Aujourd'hui, c'est TON moment !",
      "groupEmojis": "🥂 🎂 🥳",
      "text2": "On a essayé d'écrire de grands discours.",
      "text3": "On a retourné tout le dictionnaire.",
      "text4": "Mais au final, le plus simple c'était de te dire",
      "text4Adjective": "MERCI",
      "text5Entry": "Tout simplement parce que,",
      "text5Content": "Tu rends nos vies meilleures",
      "smiley": ":)",
      "wishHeading": "Joyeux Anniversaire !",
      "wishText": "De la part de nous tous. Ne change rien ! 💖",
      "carouselTitle": "Ce qu'on avait vraiment sur le cœur :",
      "outroText": "On espère que cette petite attention t'a plu.",
      "replayText": "Se refaire la scène ↺",
      "outroSmiley": ":)"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* ── collective-pro ─────────────────────────────────────── */
  {
    name: 'collective-pro',
    label: 'Collectif Pro',
    description: "Pour célébrer vos équipes avec classe : branding entreprise, signatures et export HD.",
    price: 2000,
    creditsRequired: 4,
    emoji: '🏢',
    gradient: 'linear-gradient(135deg,#1e3a5f,#0f1e30)',
    highlights: ["Logo & couleurs entreprise", "Sous-domaine personnalisé", "Contributions illimitées", "Statistiques d'engagement"],
    tags: ['collectif', 'entreprise', 'pro'],
    sortOrder: 5,
    active: true,
    featured: false,
    fields: [
      { key: 'name',         label: 'Prénom / Nom du destinataire',  type: 'text',      section: 'Intro',    placeholder: 'Prénom',                                   required: true },
      { key: 'greeting',     label: "Formule d'appel",               type: 'text',      section: 'Intro',    placeholder: 'Bonjour'                                                          },
      { key: 'greetingText', label: "Phrase d'introduction",         type: 'text',      section: 'Intro',    placeholder: "Toute l'équipe tenait à marquer le coup !"                             },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)',    type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                              },
      { key: 'musicStartTime',label: 'Démarrer à (secondes)',        type: 'starttime', section: 'Musique'                                                                                },
      { key: 'trackTitle',   label: 'Titre de la musique',           type: 'text',      section: 'Musique',  placeholder: 'Un morceau pour vous'                                          },
      { key: 'trackArtist',  label: 'Artiste',                       type: 'text',      section: 'Musique',  placeholder: "Sélection de l'équipe"                                         },
      { key: 'musicHint',    label: 'Indication musique',            type: 'text',      section: 'Musique',  placeholder: "Mettez le son pour l'ambiance 🎵"                             },
      { key: 'groupName',    label: "Nom de l'équipe / département", type: 'text',      section: 'Message',  placeholder: "Vos collègues (préférés)",                 required: true            },
      { key: 'groupMessage', label: "Message de l'équipe",           type: 'textarea',  section: 'Message',  placeholder: "Une petite pause s'impose pour célébrer cette journée !"    },
      { key: 'text2',        label: 'Phrase de transition 1',        type: 'text',      section: 'Histoire', placeholder: 'On aurait pu faire un simple e-mail groupé...'                           },
      { key: 'text3',        label: 'Phrase de transition 2',        type: 'text',      section: 'Histoire', placeholder: 'Ou laisser un post-it sur votre bureau.'                               },
      { key: 'text4',        label: 'Phrase de transition 3',        type: 'text',      section: 'Histoire', placeholder: "Mais on voulait faire les choses bien pour"                           },
      { key: 'text4Adjective',label: 'Mot clé',                      type: 'text',      section: 'Histoire', placeholder: 'VOUS'                                                          },
      { key: 'text5Entry',   label: 'Intro phrase finale',           type: 'text',      section: 'Histoire', placeholder: 'Parce que soyons honnêtes,'                                                          },
      { key: 'text5Content', label: 'Phrase finale',                 type: 'text',      section: 'Histoire', placeholder: 'Le bureau ne serait pas pareil sans vous'                                         },
      { key: 'smiley',       label: 'Ponctuation finale',            type: 'text',      section: 'Histoire', placeholder: ':)'                                                             },
      { key: 'wishHeading',  label: 'Titre du vœu',                  type: 'text',      section: 'Vœu',      placeholder: 'Très Joyeux Anniversaire !',                      required: true            },
      { key: 'wishText',     label: 'Sous-titre du vœu',             type: 'text',      section: 'Vœu',      placeholder: 'Beaucoup de réussite et de superbes projets pour cette nouvelle année 🚀'                                },
      { key: 'carouselTitle',label: 'Titre du carrousel messages',   type: 'text',      section: 'Vœu',      placeholder: "Les petits mots de l'équipe :"                             },
      { key: 'outroText',    label: 'Message de clôture',            type: 'text',      section: 'Outro',    placeholder: 'Nous espérons que cette petite parenthèse vous a fait plaisir.'                   },
      { key: 'replayText',   label: 'Texte du bouton revoir',        type: 'text',      section: 'Outro',    placeholder: "Revoir l'animation ↺"                                                      },
      { key: 'outroSmiley',  label: 'Symbole de fin',                type: 'text',      section: 'Outro',    placeholder: ':)'                                                             },
    ],
    defaultData: {
      "greeting": "Bonjour",
      "name": "Prénom",
      "greetingText": "Toute l'équipe tenait à marquer le coup !",
      "musicHint": "Mettez le son pour l'ambiance 🎵",
      "trackTitle": "Votre chansaon préférée",
      "trackArtist": "Sélection des collègues",
      "groupName": "Vos collègues (préférés)",
      "groupMessage": "Une petite pause s'impose pour célébrer cette journée !",
      "text2": "On aurait pu faire un simple e-mail groupé...",
      "text3": "Ou laisser un post-it sur votre bureau.",
      "text4": "Mais on voulait faire les choses bien pour",
      "text4Adjective": "VOUS",
      "text5Entry": "Parce que soyons honnêtes,",
      "text5Content": "Le bureau ne serait pas pareil sans vous",
      "smiley": ":)",
      "wishHeading": "Très Joyeux Anniversaire !",
      "wishText": "Beaucoup de réussite et de superbes projets pour cette nouvelle année 🚀",
      "carouselTitle": "Le petit mot de l'équipe :",
      "outroText": "Nous espérons que cette petite parenthèse vous a fait plaisir.",
      "replayText": "Revoir l'animation ↺",
      "outroSmiley": ":)"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* ── sanctuary ──────────────────────────────────────────── */
  {
    name: 'sanctuary',
    label: 'Sanctuary',
    description: 'Un cadre serein et minimaliste pour les moments qui comptent vraiment.',
    price: 6000,
    creditsRequired: 12,
    emoji: '🌸',
    gradient: 'linear-gradient(135deg,#f5f0e8,#e8d5c4)',
    highlights: ["Mise en page apaisante", "Photos & texte animés", "Musique d'ambiance", "Lien privé"],
    tags: ['élégant', 'serein', 'minimaliste'],
    sortOrder: 7,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',  placeholder: 'Élise',                           required: true },
      { key: 'greeting',       label: "Message d'accueil",          type: 'text',      section: 'Intro',  placeholder: 'Chère'                                           },
      { key: 'greetingText',   label: "Note d'introduction",        type: 'textarea',  section: 'Intro',  placeholder: 'Ce moment est pour toi.'                         },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Music',  placeholder: 'https://... .mp3'                                },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',      type: 'starttime', section: 'Music'                                                                  },
      { key: 'trackTitle',     label: 'Titre de la musique',        type: 'text',      section: 'Music'                                                                  },
      { key: 'trackArtist',    label: 'Artiste',                    type: 'text',      section: 'Music'                                                                  },
      { key: 'text2',          label: 'Première phrase',            type: 'text',      section: 'Story',  placeholder: 'Il y a des moments...'                           },
      { key: 'text3',          label: 'Deuxième phrase',            type: 'text',      section: 'Story',  placeholder: 'Qui méritent d\'être célébrés.'                  },
      { key: 'text4Adjective', label: 'Mot clé central',            type: 'text',      section: 'Story',  placeholder: 'précieux'                                        },
      { key: 'wishHeading',    label: 'Titre du vœu',               type: 'text',      section: 'Wishes', placeholder: 'Pour toi 💛',                    required: true },
      { key: 'wishText',       label: 'Sous-titre du vœu',          type: 'text',      section: 'Wishes', placeholder: 'Avec toute notre tendresse'                      },
      { key: 'outroText',      label: 'Message de fin',             type: 'text',      section: 'Outro',  placeholder: 'Que ce moment reste gravé.'                      },
      { key: 'replayText',     label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',  placeholder: 'Revoir ↺'                                        },
    ],
    defaultData: {
      greeting: 'Chère',
      name: 'Sally',
      greetingText: 'Ce moment est pour toi.',
      text2: 'Il y a des moments...',
      text3: "Qui méritent d'être célébrés.",
      text4Adjective: 'précieux',
      wishHeading: 'Pour toi 💛',
      wishText: 'Avec toute notre tendresse',
      outroText: 'Que ce moment reste gravé.',
      replayText: 'Revoir ↺',
    },
    defaultStyle: { primaryColor: '#a8856a', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'light' },
  },

  /* ── notre-film ─────────────────────────────────────────── */
  {
    name: 'notre-film',
    label: 'Notre Film',
    description: 'Un slideshow cinématique pour raconter votre histoire en images.',
    price: 1500,
    creditsRequired: 3,
    emoji: '🎬',
    gradient: 'linear-gradient(135deg,#1a1410,#3d2b1f)',
    highlights: ['Transitions cinématiques', 'Photos & vidéos mixées', 'Bande-son personnalisée', 'Format 16:9 HD'],
    tags: ['cinématique', 'vidéo', 'premium'],
    sortOrder: 8,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'Prénom du destinataire',     type: 'text',      section: 'Intro',  placeholder: 'Emma',                            required: true },
      { key: 'greeting',       label: 'Dédicace du film',           type: 'text',      section: 'Intro',  placeholder: 'Ce film est pour toi.'                           },
      { key: 'musicSrc',       label: 'Bande-son (URL .mp3)',       type: 'url',       section: 'Music',  placeholder: 'https://... .mp3'                                },
      { key: 'musicStartTime', label: 'Démarrer à (secondes)',      type: 'starttime', section: 'Music'                                                                  },
      { key: 'albumArt',       label: "Pochette / Image d'ambiance",type: 'url',       section: 'Music',  placeholder: 'https://... .jpg'                                },
      { key: 'trackTitle',     label: 'Titre de la bande-son',      type: 'text',      section: 'Music'                                                                  },
      { key: 'trackArtist',    label: 'Compositeur / Artiste',      type: 'text',      section: 'Music'                                                                  },
      { key: 'text2',          label: 'Première scène (texte)',      type: 'text',      section: 'Story',  placeholder: 'Il était une fois...'                            },
      { key: 'text3',          label: 'Deuxième scène (texte)',      type: 'text',      section: 'Story',  placeholder: 'Une personne exceptionnelle.'                    },
      { key: 'text4Adjective', label: 'Mot-clé du film',            type: 'text',      section: 'Story',  placeholder: 'extraordinaire'                                  },
      { key: 'text5Content',   label: 'Phrase titre du film',       type: 'text',      section: 'Story',  placeholder: 'Notre film, notre histoire.'                     },
      { key: 'wishHeading',    label: 'Titre du générique',         type: 'text',      section: 'Wishes', placeholder: 'Joyeux Anniversaire !',           required: true },
      { key: 'wishText',       label: 'Sous-titre du générique',    type: 'text',      section: 'Wishes', placeholder: 'Avec tout notre amour 🎬'                        },
      { key: 'outroText',      label: 'Générique de fin',           type: 'text',      section: 'Outro',  placeholder: 'Fin.'                                            },
      { key: 'replayText',     label: 'Bouton revoir',              type: 'text',      section: 'Outro',  placeholder: '↺ Revoir le film'                                },
    ],
    defaultData: {
      greeting: 'Pour toi,',
      name: 'Prénom',
      text2: 'Il était une fois...',
      text3: 'Une personne exceptionnelle.',
      text4Adjective: 'extraordinaire',
      text5Content: 'Notre film, notre histoire.',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'From my heart',
      outroText: 'Fin.',
      replayText: '↺ Revoir',
    },
    defaultStyle: { primaryColor: '#c9a84c', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'dark' },
  },
];

/* ─────────────────────────────────────────────────────────────
   Seed runner
───────────────────────────────────────────────────────────── */
async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('✓ Connecté à MongoDB\n');

  for (const tpl of TEMPLATES) {
    const { name, ...rest } = tpl;
    await Template.findOneAndUpdate(
      { name },
      { name, ...rest },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`✓ Template "${name}" mis à jour (${tpl.fields.length} champs)`);
  }

  console.log('\n──────────────────────────────────────');
  console.log(`${TEMPLATES.length} templates mis à jour avec les labels en français.`);
  console.log('──────────────────────────────────────\n');

  await mongoose.disconnect();
  console.log('Terminé.');
}

seed().catch(e => { console.error(e); process.exit(1); });
