/**
 * Seed corrector  fields en franÃ§ais pour tous les templates
 * Usage : node server/seeds/seedTemplates.js
 *   ou  : npm run seed:templates  (depuis server/)
 *
 * Ce script upsert chaque template avec :
 *   - labels de champs en franÃ§ais
 *   - donnÃ©es par dÃ©faut (defaultData) en franÃ§ais
 *   - mÃ©tadonnÃ©es (label, description, highlights, etc.)
 * Il ne supprime PAS les vÅ“ux ni les publications existantes.
 */
require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Template = require('../models/Template');

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
   DÃ©finition des templates
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
const TEMPLATES = [

  /* â”€â”€ birthday â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'birthday',
    label: 'Joyeux Anniversaire',
    description: "Animation complÃ¨te avec photos, musique et vÅ“ux personnalisÃ©s. L'incontournable.",
    price: 1000,
    priceFCFA: 1000,
    emoji: 'ðŸŽ‚',
    gradient: 'linear-gradient(135deg,#ffb4d1,#f7d59e)',
    highlights: ['Musique personnalisÃ©e (MP3)', '3 styles de typographie', 'Lien privÃ© + QR code'],
    tags: ['anniversaire', 'classique'],
    sortOrder: 1,
    active: true,
    featured: true,
    fields: [
      { key: 'name',           label: 'PrÃ©nom du destinataire',    type: 'text',      section: 'Intro',     placeholder: 'Sally',                                    required: true  },
      { key: 'greeting',       label: "Message d'accueil",         type: 'text',      section: 'Intro',     placeholder: 'Coucou'                                                         },
      { key: 'greetingText',    label: 'Note personnelle',          type: 'text',      section: 'Intro',     placeholder: "Ma star du jour !"                           , importance: 'secondary' },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)',type: 'url',       section: 'Musique',   placeholder: 'https://... .mp3'                                               },
      { key: 'musicStartTime', label: 'DÃ©marrer Ã  (secondes)',     type: 'starttime', section: 'Musique'                                                                                   },
      { key: 'albumArt',       label: "Pochette de l'album (URL)", type: 'url',       section: 'Musique',   placeholder: 'https://... .jpg'                                               },
      { key: 'trackTitle',     label: 'Titre de la musique',       type: 'text',      section: 'Musique',   placeholder: 'Happy Birthday'                                                 },
      { key: 'trackArtist',    label: 'Artiste',                   type: 'text',      section: 'Musique',   placeholder: 'Naza'                                                  },
      { key: 'musicHint',       label: 'Indication musique',        type: 'text',      section: 'Musique',   placeholder: "C'est mieux avec de la musique ðŸŽ¶"                              , importance: 'secondary' },
      { key: 'text1',           label: "Accroche principale",       type: 'text',      section: 'Message',   placeholder: "C'est ton anniversaire !!! ðŸŽ‰"                                  , importance: 'secondary' },
      { key: 'waName',          label: 'Nom du contact WhatsApp',  type: 'text',      section: 'Message',   placeholder: 'PrÃ©nom'                                                                 , importance: 'secondary' },
      { key: 'textInChatBox',  label: 'Message WhatsApp',          type: 'textarea',  section: 'Message',   placeholder: "Joyeux anniversaire !!! ðŸŽ‰ Je te souhaite le meileur.. blah blah blah !" },
      { key: 'text2',           label: "Phrase d'histoire 1",       type: 'text',      section: 'Histoire',  placeholder: "C'est ce que j'allais t'Ã©crire.."                                         , importance: 'secondary' },
      { key: 'text3',           label: "Phrase d'histoire 2",       type: 'text',      section: 'Histoire',  placeholder: 'Et puis je me suis arrÃªtÃ©.'                                       , importance: 'secondary' },
      { key: 'text4',           label: "Phrase d'histoire 3",       type: 'text',      section: 'Histoire',  placeholder: "J'ai rÃ©alisÃ© que je voulais faire un truc "                                  , importance: 'secondary' },
      { key: 'text4Adjective',  label: "Mot clÃ© de l'histoire",     type: 'text',      section: 'Histoire',  placeholder: 'Unique'                                                          , importance: 'secondary' },
      { key: 'text5Entry',      label: 'Intro phrase finale',       type: 'text',      section: 'Histoire',  placeholder: 'Parce que,'                                                     , importance: 'secondary' },
      { key: 'text5Content',    label: 'Phrase finale',             type: 'text',      section: 'Histoire',  placeholder: 'Tu es spÃ©ciale'                                            , importance: 'secondary' },
      { key: 'smiley',          label: 'Emoji principal',           type: 'text',      section: 'Histoire',  placeholder: ':)'                                                             , importance: 'secondary' },
      { key: 'bigTextPart1',  label: 'PremiÃ¨re Lettre', type: 'text', section: 'Histoire', placeholder: 'S' , importance: 'secondary' },
      { key: 'bigTextPart2',  label: 'DeuxiÃ¨me Lettre', type: 'text', section: 'Histoire', placeholder: 'O' , importance: 'secondary' },
      { key: 'imagePath',      label: 'Photo principale',          type: 'url',       section: 'CÃ©lÃ©bration', placeholder: 'https://... .jpg'                                           },
      { key: 'photo1',         label: 'Photo gauche',              type: 'url',       section: 'CÃ©lÃ©bration', placeholder: 'https://... .jpg'                                           },
      { key: 'photo2',         label: 'Photo droite',              type: 'url',       section: 'CÃ©lÃ©bration', placeholder: 'https://... .jpg'                                           },
      { key: 'imageLayout',     label: 'Disposition photos',        type: 'layout',    section: 'CÃ©lÃ©bration',
        options: [
          { value: 'grid',      label: 'Grille',  icon: 'â–¦' , importance: 'secondary' },
          { value: 'stack',     label: 'Pile',    icon: 'â§‰' },
          { value: 'spotlight', label: 'Focus',   icon: 'â—Ž' },
          { value: 'row',       label: 'RangÃ©e',  icon: 'â–¬' },
        ]
      },
      { key: 'wishHeading',    label: 'Titre du vÅ“u',              type: 'text',      section: 'VÅ“u',       placeholder: 'Joyeux Anniversaire !',                     required: true      },
      { key: 'wishText',       label: 'Sous-titre du vÅ“u',         type: 'text',      section: 'VÅ“u',       placeholder: 'Bel Ã¢ge Ã  toi !'                                       },
      { key: 'wish1',          label: 'VÅ“u 1',                     type: 'textarea',  section: 'VÅ“ux',      placeholder: 'Ton premier vÅ“uâ€¦'                                                     },
      { key: 'wish2',          label: 'VÅ“u 2',                     type: 'textarea',  section: 'VÅ“ux',      placeholder: 'Ton deuxiÃ¨me vÅ“uâ€¦'                                                    },
      { key: 'wish3',          label: 'VÅ“u 3',                     type: 'textarea',  section: 'VÅ“ux',      placeholder: 'Ton troisiÃ¨me vÅ“uâ€¦'                                                   },
      { key: 'outroText',       label: 'Message de fin',            type: 'text',      section: 'Outro',     placeholder: "Bon, J'espÃ¨re que tu as kiffÃ© !"                               , importance: 'secondary' },
      { key: 'replayText',      label: 'Texte du bouton revoir',    type: 'text',      section: 'Outro',     placeholder: 'Clique ici pour revoir â†º'                                           , importance: 'secondary' },
      { key: 'outroSmiley',     label: 'Emoji de fin',              type: 'text',      section: 'Outro',     placeholder: ':)'                                                             , importance: 'secondary' },
    ],
    defaultData: {
      greeting: 'Coucou',
      name: 'Sally',
      greetingText: "Ma star du jour !",
      musicHint: "C'est mieux avec de la musique ðŸŽ¶",
      text1: "C'est ton anniversaire !!! ðŸŽ‰",
      waName: 'Sally',
      waAvatar: 'S',
      textInChatBox: "Joyeux anniversaire !!! ðŸŽ‰ Je te souhaite le meileur.. blah blah blah !!",
      text2: "C'est ce que j'allais t'Ã©crire..",
      text3: 'Et puis je me suis arrÃªtÃ©.',
      text4: "J'ai rÃ©alisÃ© que je voulais faire un truc ",
      text4Adjective: 'Unique',
      text5Entry: 'Parce que,',
      text5Content: 'Tu es SpÃ©ciale',
      smiley: ':)',
      bigTextPart1: 'S', bigTextPart2: 'O',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'Bel Ã¢ge Ã  toi !',
      wish1: 'Que cette nouvelle annÃ©e de ta vie soit remplie de joie, de lumiÃ¨re et de toutes ces petites choses qui font sourire.',
      wish2: 'Tu mÃ©rites tout le bonheur du monde, et je souhaite que chaque journÃ©e t\'apporte quelque chose de beau.',
      wish3: 'Joyeux anniversaire du fond du cÅ“ur. ðŸŽ‚âœ¨',
      outroText: "J'espÃ¨re que tu as kiffÃ© !",
      replayText: 'Revoir â†º',
      outroSmiley: ':)',
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ wall-of-wishes â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'wall-of-wishes',
    label: 'Mur classique',
    description: "Un mur interactif oÃ¹ chacun colle son message  comme des post-its numÃ©riques.",
    price: 5000,
    priceFCFA: 5000,
    emoji: 'ðŸ’Œ',
    gradient: 'linear-gradient(135deg,#fdf6c3,#fce4ec,#ede7f6)',
    highlights: ["Jusqu'Ã  30 contributeurs", 'ModÃ©ration avant publication', '6 couleurs de post-it', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif'],
    sortOrder: 2,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'PrÃ©nom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Partagez ce lien  laissez votre message ici.' },
    ],
    defaultData: {
      titleName: 'PrÃ©nom',
      subtitle: 'Partagez ce lien  chacun peut laisser son mot sur ce mur.',
    },
    defaultStyle: { primaryColor: '#E11D48', accentColor: '#E11D48', fontFamily: 'Plus Jakarta Sans', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ wall-of-wishes-modern â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'wall-of-wishes-modern',
    label: 'Mur Moderne',
    description: "Mur classique glassmorphisme sur fond dÃ©gradÃ© lavande-rose. Cards sociales Ã©lÃ©gantes avec avatar et rÃ´le.",
    price: 5000,
    priceFCFA: 5000,
    emoji: 'ðŸ’¬',
    gradient: 'linear-gradient(135deg,#ccc0f5,#e8b0d8,#f5a8be)',
    highlights: ['Design glassmorphisme', 'Champ relation/rÃ´le', 'Barre de cagnotte intÃ©grÃ©e', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif', 'moderne'],
    sortOrder: 9,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'PrÃ©nom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'eyebrow',    label: 'Badge en haut du mur',   type: 'text',     section: 'Mur', placeholder: 'âœ¦ Mur classique' , importance: 'secondary' },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Partagez ce lien  laissez votre message ici.' },
    ],
    defaultData: {
      titleName: 'PrÃ©nom',
      eyebrow: 'âœ¦ Mur classique',
      subtitle: 'Partagez ce lien  chacun peut laisser son mot sur ce mur.',
    },
    defaultStyle: { primaryColor: '#7C5CC9', accentColor: '#7C5CC9', fontFamily: 'Plus Jakarta Sans', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ wall-of-wishes-space â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'wall-of-wishes-space',
    label: 'Mur Spatial',
    description: "Canvas infini de vÅ“ux style Polaroid sur fond corail. Pan, zoom et vue dÃ©tail au clic.",
    price: 5000,
    priceFCFA: 5000,
    emoji: 'ðŸš€',
    gradient: 'linear-gradient(135deg,#ff8060,#ff4878,#d83070)',
    highlights: ['Canvas infini pan + zoom', 'Cartes Polaroid Ã©parpillÃ©es', 'Vue dÃ©tail au clic', "Partage par lien d'invitation"],
    tags: ['collectif', 'interactif', 'spatial'],
    sortOrder: 10,
    active: true,
    featured: false,
    fields: [
      { key: 'titleName', label: 'PrÃ©nom du destinataire', type: 'text',     section: 'Mur', placeholder: 'Sarah',                              required: true },
      { key: 'eyebrow',    label: 'Badge en haut du mur',   type: 'text',     section: 'Mur', placeholder: 'âœ¦ Mur classique' , importance: 'secondary' },
      { key: 'subtitle',  label: 'Sous-titre du mur',      type: 'textarea', section: 'Mur', placeholder: 'Glisse pour explorer Â· Clique pour lire.' },
    ],
    defaultData: {
      titleName: 'PrÃ©nom',
      eyebrow: 'âœ¦ Mur classique',
      subtitle: 'Glisse pour explorer Â· Clique sur une carte pour lire le vÅ“u.',
    },
    defaultStyle: { primaryColor: '#ff4878', accentColor: '#ff8060', fontFamily: 'Inter', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ special â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'special',
    label: 'VÅ“u SpÃ©cial',
    description: "Montrez on a une personne Ã  quel point elle est unique !",
    price: 1000,
    priceFCFA: 1000,
    emoji: 'âœ¦',
    gradient: 'linear-gradient(135deg,#a18cd1,#fbc2eb)',
    highlights: ['ThÃ¨me sur-mesure', 'Particules & transitions premium', 'Export vidÃ©o MP4 HD', 'Photos illimitÃ©es'],
    tags: ['premium', 'spÃ©cial'],
    sortOrder: 3,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'PrÃ©nom du destinataire',     type: 'text',      section: 'Intro',    placeholder: 'Sally',                                                     required: true },
      { key: 'greeting',       label: "Message d'accueil",          type: 'text',      section: 'Intro',    placeholder: 'Coucou'                                                                         },
      { key: 'greetingText',    label: 'Note personnelle',           type: 'text',      section: 'Intro',    placeholder: "On a menÃ© notre petite enquÃªte.."                                                 , importance: 'secondary' },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                                               },
      { key: 'musicStartTime', label: 'DÃ©marrer Ã  (secondes)',      type: 'starttime', section: 'Musique'                                                                                                  },
      { key: 'albumArt',       label: "Pochette de l'album (URL)",  type: 'url',       section: 'Musique',  placeholder: 'https://... .jpg'                                                               },
      { key: 'trackTitle',     label: 'Titre de la musique',        type: 'text',      section: 'Musique',  placeholder: 'Gold'                                                                           },
      { key: 'trackArtist',    label: 'Artiste',                    type: 'text',      section: 'Musique',  placeholder: 'Spandau Ballet'                                                                 },
      { key: 'musicHint',       label: 'Indication musique',         type: 'text',      section: 'Musique',  placeholder: "C'est mieux avec de la musique ðŸŽ¶"                                              , importance: 'secondary' },
      { key: 'text1',           label: 'Accroche avant la recherche',type: 'text',      section: 'Google',   placeholder: 'Et on a lancÃ© une rechercheâ€¦ ðŸ”'                                                    , importance: 'secondary' },
      { key: 'searchQuery',     label: 'RequÃªte Google',             type: 'text',      section: 'Google',   placeholder: 'la meilleure personne du monde'                                                    , importance: 'secondary' },
      { key: 'result1Title',    label: 'Titre rÃ©sultat #1',          type: 'text',      section: 'Google',   placeholder: 'La personne la plus exceptionnelle recensÃ©e sur Terre'                          , importance: 'secondary' },
      { key: 'result1Snippet',  label: 'Extrait rÃ©sultat #1',        type: 'textarea',  section: 'Google',   placeholder: "AprÃ¨s analyse de 8 milliards de profils, les experts s'accordentâ€¦"             , importance: 'secondary' },
      { key: 'result1Domain',   label: 'Domaine rÃ©sultat #1',        type: 'text',      section: 'Google',   placeholder: 'patrimoine-de-l-humanite.org'                                                                 , importance: 'secondary' },
      { key: 'result1Rating',   label: 'Note rÃ©sultat #1',           type: 'text',      section: 'Google',   placeholder: "â­ 5,0/5 Â· Avis validÃ©s par l'univers entier"                                                , importance: 'secondary' },
      { key: 'result2Title',    label: 'Titre rÃ©sultat #2',          type: 'text',      section: 'Google',   placeholder: 'DÃ©finition de Â« Parfaite Â»  Dictionnaire IllustrÃ©'                                   , importance: 'secondary' },
      { key: 'result2Snippet',  label: 'Extrait rÃ©sultat #2',        type: 'textarea',  section: 'Google',   placeholder: "L'AcadÃ©mie a rÃ©cemment mis Ã  jour sa dÃ©finition du mot \"parfaite\" pour y intÃ©grer directement une photo d'elle."    , importance: 'secondary' },
      { key: 'result3Title',    label: 'Titre rÃ©sultat #3',          type: 'text',      section: 'Google',   placeholder: 'Guinness World Records  CÅ“ur en or certifiÃ©'                          , importance: 'secondary' },
      { key: 'result3Snippet',  label: 'Extrait rÃ©sultat #3',        type: 'textarea',  section: 'Google',   placeholder: "Record officiellement validÃ© : aucune technologie actuelle ne permet de mesurer l'Ã©tendue totale de sa bienveillance."                             , importance: 'secondary' },
      { key: 'text2',           label: "Phrase de transition 1",     type: 'text',      section: 'Histoire', placeholder: 'On a fouillÃ© le web entier.'                                                          , importance: 'secondary' },
      { key: 'text3',           label: "Phrase de transition 2",     type: 'text',      section: 'Histoire', placeholder: 'PassÃ© au crible des milliards de rÃ©sultats.'                                                    , importance: 'secondary' },
      { key: 'text4',           label: "Phrase de transition 3",     type: 'text',      section: 'Histoire', placeholder: "Mais l'Ã©vidence Ã©tait lÃ , c'Ã©tait"                                               , importance: 'secondary' },
      { key: 'text4Adjective',  label: 'Adjectif clÃ©',               type: 'text',      section: 'Histoire', placeholder: 'TOI'                                                                            , importance: 'secondary' },
      { key: 'text5Entry',      label: 'Intro phrase finale',        type: 'text',      section: 'Histoire', placeholder: 'Parce que,'                                                                     , importance: 'secondary' },
      { key: 'text5Content',    label: 'Phrase finale',              type: 'text',      section: 'Histoire', placeholder: 'Tu es unique'                                                                   , importance: 'secondary' },
      { key: 'bigTextPart1',  label: 'PremiÃ¨re Lettre', type: 'text', section: 'Histoire', placeholder: 'S' , importance: 'secondary' },
      { key: 'bigTextPart2',  label: 'DeuxiÃ¨me Lettre', type: 'text', section: 'Histoire', placeholder: 'O' , importance: 'secondary' },
      { key: 'smiley',          label: 'Emoji principal',            type: 'text',      section: 'Histoire', placeholder: ':)'                                                                             , importance: 'secondary' },
      { key: 'wishHeading',    label: 'Titre du vÅ“u',               type: 'text',      section: 'VÅ“u',      placeholder: 'Joyeux Anniversaire !',                             required: true             },
      { key: 'wishText',       label: 'Sous-titre du vÅ“u',          type: 'text',      section: 'VÅ“u',      placeholder: 'Profite Ã  fond, le meilleur reste Ã  venir ðŸš€'                                                   },
      { key: 'outroText',       label: 'Message de fin',             type: 'text',      section: 'Outro',    placeholder: "On espÃ¨re que cette petite surprise t'a fait sourire !"                                                      , importance: 'secondary' },
      { key: 'replayText',      label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',    placeholder: "Revoir â†º"                                                                       , importance: 'secondary' },
      { key: 'outroSmiley',     label: 'Emoji de fin',               type: 'text',      section: 'Outro',    placeholder: 'ðŸŽ‰'                                                                             , importance: 'secondary' },
    ],
    defaultData: {
      "greeting": "Coucou",
      "name": "Sally",
      "greetingText": "On a menÃ© notre petite enquÃªte...",
      "musicHint": "C'est mieux avec le son activÃ© ðŸŽ¶",
      "text1": "Et on a lancÃ© une rechercheâ€¦ ðŸ”",
      "trackTitle": "Happy Birthday",
      "trackArtist": "Naza",
      "searchQuery": "la meilleure personne au monde",
      "result1Title": "La personne la plus exceptionnelle recensÃ©e sur Terre",
      "result1Snippet": "AprÃ¨s l'analyse approfondie de 8 milliards de profils, les experts s'accordent sur un rÃ©sultat incontestable.",
      "result1Domain": "patrimoine-de-l-humanite.org",
      "result1Rating": "â­ 5,0/5 Â· Avis validÃ©s par l'univers entier",
      "result2Title": "DÃ©finition de Â« Parfaite Â»  Dictionnaire IllustrÃ©",
      "result2Snippet": "L'AcadÃ©mie a rÃ©cemment mis Ã  jour sa dÃ©finition du mot \"parfaite\" pour y intÃ©grer directement une photo d'elle.",
      "result3Title": "Guinness World Records  CÅ“ur en or certifiÃ©",
      "result3Snippet": "Record officiellement validÃ© : aucune technologie actuelle ne permet de mesurer l'Ã©tendue totale de sa bienveillance.",
      "text2": "On a fouillÃ© le web entier.",
      "text3": "PassÃ© au crible des milliards de rÃ©sultats.",
      "text4": "Mais l'Ã©vidence Ã©tait lÃ , c'Ã©tait",
      "text4Adjective": "TOI",
      "text5Entry": "Tout simplement parce que,",
      "text5Content": "Tu es unique",
      "smiley": ":)",
      "wishHeading": "Joyeux Anniversaire !",
      "wishText": "Profite Ã  fond, le meilleur reste Ã  venir ðŸš€",
      "outroText": "On espÃ¨re que cette petite surprise t'a fait sourire !",
      "replayText": "Revoir l'animation â†º",
      "outroSmiley": ":)"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ forever (Hommage) â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'forever',
    label: 'Hommage',
    description: 'Sobre, digne, intemporel. Cadres dorÃ©s et typographie Ã©lÃ©gante pour crÃ©er un souvenir mÃ©morable.',
    price: 1000,
    priceFCFA: 1000,
    emoji: 'âœ¦',
    gradient: 'linear-gradient(135deg,#1e3a5f,#2c2218)',
    highlights: ['Cadres & typographie classiques', 'Citation ou poÃ¨me central', 'Galerie chronologique', 'Lien privÃ© non-indexÃ©'],
    tags: ['hommage', 'mÃ©morial'],
    sortOrder: 6,
    active: true,
    featured: false,
    //
    fields: [
      { key: 'name',         label: 'PrÃ©nom | Nom',      type: 'text',     section: 'Intro',  placeholder: "Sally",     required: true },
      { key: 'greeting',     label: '', type: 'text', section: 'Intro', placeholder: "Hey"},
      { key: 'greetingText',  label: "Salutation", type: 'text', section: 'Intro', importance: 'secondary' }
    ],
    defaultData: {
      "greeting": "hey,",
      "name": "Sally",
      "greetingText": "Hey",
      "countdownLabel": "Ensemble depuis",
      "keyNumber": "âˆž",
      "countdownUnit": "jours",
      "countdownSince": "depuis le premier jour",
      "imagePath": "",
      "photoCaption": "Toujours aussi belle.",
      "photoSub": "Ã  chaque regard",
      "senderName": "de toi qui t'aime",
      "outroText": "Gros Bisous !",
      "replayText": "Recommencer"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ collective-family â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'collective-family',
    label: 'Collectif Famille',
    description: "Chaque proche ajoute son message et sa photo  un souvenir partagÃ© jusqu'Ã  50 contributeurs.",
    price: 2000,
    priceFCFA: 2000,
    emoji: 'ðŸ‘¨â€ðŸ‘©â€ðŸ‘§â€ðŸ‘¦',
    gradient: 'linear-gradient(135deg,#f093fb,#f5576c)',
    highlights: ["Jusqu'Ã  50 contributeurs", 'Messages texte, audio ou vidÃ©o', 'Galerie photos partagÃ©e', 'Album tÃ©lÃ©chargeable PDF'],
    tags: ['collectif', 'famille'],
    sortOrder: 4,
    active: true,
    featured: false,
    fields: [
      { key: 'name',         label: 'PrÃ©nom du destinataire',     type: 'text',      section: 'Intro',    placeholder: 'Sally',                                        required: true },
      { key: 'greeting',     label: "Message d'accueil",          type: 'text',      section: 'Intro',    placeholder: 'Coucou'                                                        },
      { key: 'greetingText',  label: 'Note personnelle',           type: 'text',      section: 'Intro',    placeholder: "Notre star du jour !"                                         , importance: 'secondary' },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                              },
      { key: 'musicStartTime',label: 'DÃ©marrer Ã  (secondes)',     type: 'starttime', section: 'Musique'                                                                                },
      { key: 'trackTitle',   label: 'Titre de la musique',        type: 'text',      section: 'Musique',  placeholder: 'Notre hymne'                                                 },
      { key: 'trackArtist',  label: 'Artiste',                    type: 'text',      section: 'Musique',  placeholder: 'Team Paiya'                                               },
      { key: 'musicHint',     label: 'Indication musique',         type: 'text',      section: 'Musique',  placeholder: "Mets le son, l'ambiance est meilleure ðŸŽ¶"                             , importance: 'secondary' },
      { key: 'groupName',    label: 'Nom du groupe / famille',    type: 'text',      section: 'Message',  placeholder: 'Ta team de choc',                         required: true            },
      { key: 'groupMessage', label: 'Message du groupe',          type: 'textarea',  section: 'Message',  placeholder: "Aujourd'hui, c'est TON moment !"                  },
      { key: 'groupEmojis',   label: 'Emojis du groupe',           type: 'text',      section: 'Message',  placeholder: 'ðŸ¥‚ ðŸŽ‚ ðŸ¥³'                                                     , importance: 'secondary' },
      { key: 'text2',         label: "Phrase d'histoire 1",        type: 'text',      section: 'Histoire', placeholder: "On a essayÃ© d'Ã©crire de grands discours."                                        , importance: 'secondary' },
      { key: 'text3',         label: "Phrase d'histoire 2",        type: 'text',      section: 'Histoire', placeholder: 'On a retournÃ© tout le dictionnaire.'                                      , importance: 'secondary' },
      { key: 'text4',         label: "Phrase d'histoire 3",        type: 'text',      section: 'Histoire', placeholder: "Mais au final, le plus simple c'Ã©tait de te dire"                                 , importance: 'secondary' },
      { key: 'text4Adjective', label: "Mot clÃ© de l'histoire",     type: 'text',      section: 'Histoire', placeholder: 'merci'                                                         , importance: 'secondary' },
      { key: 'text5Entry',    label: 'Intro phrase finale',        type: 'text',      section: 'Histoire', placeholder: 'Tout simplement parce que,'                                                    , importance: 'secondary' },
      { key: 'text5Content',  label: 'Phrase finale',              type: 'text',      section: 'Histoire', placeholder: 'Tu rends nos vies meilleures'                                           , importance: 'secondary' },
      { key: 'smiley',        label: 'Emoji principal',            type: 'text',      section: 'Histoire', placeholder: ':)'                                                            , importance: 'secondary' },
      { key: 'wishHeading',  label: 'Titre du vÅ“u',               type: 'text',      section: 'VÅ“u',      placeholder: 'Joyeux Anniversaire !',              required: true            },
      { key: 'wishText',     label: 'Sous-titre du vÅ“u',          type: 'text',      section: 'VÅ“u',      placeholder: 'De la part de nous tous. Ne change rien ! ðŸ’–'                             },
      { key: 'carouselTitle',label: 'Titre du carrousel vÅ“ux',    type: 'text',      section: 'VÅ“u',      placeholder: "Ce qu'on avait vraiment sur le cÅ“ur :"                                },
      { key: 'outroText',     label: 'Message de fin',             type: 'text',      section: 'Outro',    placeholder: "On espÃ¨re que cette petite attention t'a plu."                              , importance: 'secondary' },
      { key: 'replayText',    label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',    placeholder: 'Se refaire la scÃ¨ne â†º'                                          , importance: 'secondary' },
      { key: 'outroSmiley',   label: 'Emoji de fin',               type: 'text',      section: 'Outro',    placeholder: ':)'                                                            , importance: 'secondary' },
    ],
    defaultData: {
      "greeting": "Coucou",
      "name": "Sally",
      "greetingText": "Notre star du jour !",
      "musicHint": "Mets le son, l'ambiance est meilleure ðŸŽ¶",
      "trackTitle": "Notre Hymne",
      "trackArtist": "Team Paiya",
      "groupName": "Ta team de choc",
      "groupMessage": "Aujourd'hui, c'est TON moment !",
      "groupEmojis": "ðŸ¥‚ ðŸŽ‚ ðŸ¥³",
      "text2": "On a essayÃ© d'Ã©crire de grands discours.",
      "text3": "On a retournÃ© tout le dictionnaire.",
      "text4": "Mais au final, le plus simple c'Ã©tait de te dire",
      "text4Adjective": "MERCI",
      "text5Entry": "Tout simplement parce que,",
      "text5Content": "Tu rends nos vies meilleures",
      "smiley": ":)",
      "wishHeading": "Joyeux Anniversaire !",
      "wishText": "De la part de nous tous. Ne change rien ! ðŸ’–",
      "carouselTitle": "Ce qu'on avait vraiment sur le cÅ“ur :",
      "outroText": "On espÃ¨re que cette petite attention t'a plu.",
      "replayText": "Se refaire la scÃ¨ne â†º",
      "outroSmiley": ":)"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ collective-pro â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'collective-pro',
    label: 'Collectif Pro',
    description: "Pour cÃ©lÃ©brer vos Ã©quipes avec classe : branding entreprise, signatures et export HD.",
    price: 2000,
    priceFCFA: 2000,
    emoji: 'ðŸ¢',
    gradient: 'linear-gradient(135deg,#1e3a5f,#0f1e30)',
    highlights: ["Logo & couleurs entreprise", "Sous-domaine personnalisÃ©", "Contributions illimitÃ©es", "Statistiques d'engagement"],
    tags: ['collectif', 'entreprise', 'pro'],
    sortOrder: 5,
    active: true,
    featured: false,
    fields: [
      { key: 'name',         label: 'PrÃ©nom / Nom du destinataire',  type: 'text',      section: 'Intro',    placeholder: 'PrÃ©nom',                                   required: true },
      { key: 'greeting',     label: "Formule d'appel",               type: 'text',      section: 'Intro',    placeholder: 'Bonjour'                                                          },
      { key: 'greetingText',  label: "Phrase d'introduction",         type: 'text',      section: 'Intro',    placeholder: "Toute l'Ã©quipe tenait Ã  marquer le coup !"                             , importance: 'secondary' },
      { key: 'musicSrc',     label: 'Fichier musical (URL .mp3)',    type: 'url',       section: 'Musique',  placeholder: 'https://... .mp3'                                              },
      { key: 'musicStartTime',label: 'DÃ©marrer Ã  (secondes)',        type: 'starttime', section: 'Musique'                                                                                },
      { key: 'trackTitle',   label: 'Titre de la musique',           type: 'text',      section: 'Musique',  placeholder: 'Un morceau pour vous'                                          },
      { key: 'trackArtist',  label: 'Artiste',                       type: 'text',      section: 'Musique',  placeholder: "SÃ©lection de l'Ã©quipe"                                         },
      { key: 'musicHint',     label: 'Indication musique',            type: 'text',      section: 'Musique',  placeholder: "Mettez le son pour l'ambiance ðŸŽµ"                             , importance: 'secondary' },
      { key: 'groupName',    label: "Nom de l'Ã©quipe / dÃ©partement", type: 'text',      section: 'Message',  placeholder: "Vos collÃ¨gues (prÃ©fÃ©rÃ©s)",                 required: true            },
      { key: 'groupMessage', label: "Message de l'Ã©quipe",           type: 'textarea',  section: 'Message',  placeholder: "Une petite pause s'impose pour cÃ©lÃ©brer cette journÃ©e !"    },
      { key: 'text2',         label: 'Phrase de transition 1',        type: 'text',      section: 'Histoire', placeholder: 'On aurait pu faire un simple e-mail groupÃ©...'                           , importance: 'secondary' },
      { key: 'text3',         label: 'Phrase de transition 2',        type: 'text',      section: 'Histoire', placeholder: 'Ou laisser un post-it sur votre bureau.'                               , importance: 'secondary' },
      { key: 'text4',         label: 'Phrase de transition 3',        type: 'text',      section: 'Histoire', placeholder: "Mais on voulait faire les choses bien pour"                           , importance: 'secondary' },
      { key: 'text4Adjective', label: 'Mot clÃ©',                      type: 'text',      section: 'Histoire', placeholder: 'VOUS'                                                          , importance: 'secondary' },
      { key: 'text5Entry',    label: 'Intro phrase finale',           type: 'text',      section: 'Histoire', placeholder: 'Parce que soyons honnÃªtes,'                                                          , importance: 'secondary' },
      { key: 'text5Content',  label: 'Phrase finale',                 type: 'text',      section: 'Histoire', placeholder: 'Le bureau ne serait pas pareil sans vous'                                         , importance: 'secondary' },
      { key: 'smiley',        label: 'Ponctuation finale',            type: 'text',      section: 'Histoire', placeholder: ':)'                                                             , importance: 'secondary' },
      { key: 'wishHeading',  label: 'Titre du vÅ“u',                  type: 'text',      section: 'VÅ“u',      placeholder: 'TrÃ¨s Joyeux Anniversaire !',                      required: true            },
      { key: 'wishText',     label: 'Sous-titre du vÅ“u',             type: 'text',      section: 'VÅ“u',      placeholder: 'Beaucoup de rÃ©ussite et de superbes projets pour cette nouvelle annÃ©e ðŸš€'                                },
      { key: 'carouselTitle',label: 'Titre du carrousel messages',   type: 'text',      section: 'VÅ“u',      placeholder: "Les petits mots de l'Ã©quipe :"                             },
      { key: 'outroText',     label: 'Message de clÃ´ture',            type: 'text',      section: 'Outro',    placeholder: 'Nous espÃ©rons que cette petite parenthÃ¨se vous a fait plaisir.'                   , importance: 'secondary' },
      { key: 'replayText',    label: 'Texte du bouton revoir',        type: 'text',      section: 'Outro',    placeholder: "Revoir l'animation â†º"                                                      , importance: 'secondary' },
      { key: 'outroSmiley',   label: 'Symbole de fin',                type: 'text',      section: 'Outro',    placeholder: ':)'                                                             , importance: 'secondary' },
    ],
    defaultData: {
      "greeting": "Bonjour",
      "name": "PrÃ©nom",
      "greetingText": "Toute l'Ã©quipe tenait Ã  marquer le coup !",
      "musicHint": "Mettez le son pour l'ambiance ðŸŽµ",
      "trackTitle": "Votre chansaon prÃ©fÃ©rÃ©e",
      "trackArtist": "SÃ©lection des collÃ¨gues",
      "groupName": "Vos collÃ¨gues (prÃ©fÃ©rÃ©s)",
      "groupMessage": "Une petite pause s'impose pour cÃ©lÃ©brer cette journÃ©e !",
      "text2": "On aurait pu faire un simple e-mail groupÃ©...",
      "text3": "Ou laisser un post-it sur votre bureau.",
      "text4": "Mais on voulait faire les choses bien pour",
      "text4Adjective": "VOUS",
      "text5Entry": "Parce que soyons honnÃªtes,",
      "text5Content": "Le bureau ne serait pas pareil sans vous",
      "smiley": ":)",
      "wishHeading": "TrÃ¨s Joyeux Anniversaire !",
      "wishText": "Beaucoup de rÃ©ussite et de superbes projets pour cette nouvelle annÃ©e ðŸš€",
      "carouselTitle": "Le petit mot de l'Ã©quipe :",
      "outroText": "Nous espÃ©rons que cette petite parenthÃ¨se vous a fait plaisir.",
      "replayText": "Revoir l'animation â†º",
      "outroSmiley": ":)"
    },
    defaultStyle: { primaryColor: '#E11D74', accentColor: '#F5B544', fontFamily: 'Outfit', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ sanctuary â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'sanctuary',
    label: 'Sanctuary',
    description: 'Un cadre serein et minimaliste pour les moments qui comptent vraiment.',
    price: 6000,
    priceFCFA: 6000,
    emoji: 'ðŸŒ¸',
    gradient: 'linear-gradient(135deg,#f5f0e8,#e8d5c4)',
    highlights: ["Mise en page apaisante", "Photos & texte animÃ©s", "Musique d'ambiance", "Lien privÃ©"],
    tags: ['Ã©lÃ©gant', 'serein', 'minimaliste'],
    sortOrder: 7,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'PrÃ©nom du destinataire',     type: 'text',      section: 'Intro',  placeholder: 'Ã‰lise',                           required: true },
      { key: 'greeting',       label: "Message d'accueil",          type: 'text',      section: 'Intro',  placeholder: 'ChÃ¨re'                                           },
      { key: 'greetingText',    label: "Note d'introduction",        type: 'textarea',  section: 'Intro',  placeholder: 'Ce moment est pour toi.'                         , importance: 'secondary' },
      { key: 'musicSrc',       label: 'Fichier musical (URL .mp3)', type: 'url',       section: 'Music',  placeholder: 'https://... .mp3'                                },
      { key: 'musicStartTime', label: 'DÃ©marrer Ã  (secondes)',      type: 'starttime', section: 'Music'                                                                  },
      { key: 'trackTitle',     label: 'Titre de la musique',        type: 'text',      section: 'Music'                                                                  },
      { key: 'trackArtist',    label: 'Artiste',                    type: 'text',      section: 'Music'                                                                  },
      { key: 'text2',           label: 'PremiÃ¨re phrase',            type: 'text',      section: 'Story',  placeholder: 'Il y a des moments...'                           , importance: 'secondary' },
      { key: 'text3',           label: 'DeuxiÃ¨me phrase',            type: 'text',      section: 'Story',  placeholder: 'Qui mÃ©ritent d\'Ãªtre cÃ©lÃ©brÃ©s.'                  , importance: 'secondary' },
      { key: 'text4Adjective',  label: 'Mot clÃ© central',            type: 'text',      section: 'Story',  placeholder: 'prÃ©cieux'                                        , importance: 'secondary' },
      { key: 'wishHeading',    label: 'Titre du vÅ“u',               type: 'text',      section: 'Wishes', placeholder: 'Pour toi ðŸ’›',                    required: true },
      { key: 'wishText',       label: 'Sous-titre du vÅ“u',          type: 'text',      section: 'Wishes', placeholder: 'Avec toute notre tendresse'                      },
      { key: 'outroText',       label: 'Message de fin',             type: 'text',      section: 'Outro',  placeholder: 'Que ce moment reste gravÃ©.'                      , importance: 'secondary' },
      { key: 'replayText',      label: 'Texte du bouton revoir',     type: 'text',      section: 'Outro',  placeholder: 'Revoir â†º'                                        , importance: 'secondary' },
    ],
    defaultData: {
      greeting: 'ChÃ¨re',
      name: 'Sally',
      greetingText: 'Ce moment est pour toi.',
      text2: 'Il y a des moments...',
      text3: "Qui mÃ©ritent d'Ãªtre cÃ©lÃ©brÃ©s.",
      text4Adjective: 'prÃ©cieux',
      wishHeading: 'Pour toi ðŸ’›',
      wishText: 'Avec toute notre tendresse',
      outroText: 'Que ce moment reste gravÃ©.',
      replayText: 'Revoir â†º',
    },
    defaultStyle: { primaryColor: '#a8856a', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'light' },
  },

  /* â”€â”€ notre-film â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
  {
    name: 'notre-film',
    label: 'Notre Film',
    description: 'Un slideshow cinÃ©matique pour raconter votre histoire en images.',
    price: 1500,
    priceFCFA: 1500,
    emoji: 'ðŸŽ¬',
    gradient: 'linear-gradient(135deg,#1a1410,#3d2b1f)',
    highlights: ['Transitions cinÃ©matiques', 'Photos & vidÃ©os mixÃ©es', 'Bande-son personnalisÃ©e', 'Format 16:9 HD'],
    tags: ['cinÃ©matique', 'vidÃ©o', 'premium'],
    sortOrder: 8,
    active: true,
    featured: false,
    fields: [
      { key: 'name',           label: 'PrÃ©nom du destinataire',     type: 'text',      section: 'Intro',  placeholder: 'Emma',                            required: true },
      { key: 'greeting',       label: 'DÃ©dicace du film',           type: 'text',      section: 'Intro',  placeholder: 'Ce film est pour toi.'                           },
      { key: 'musicSrc',       label: 'Bande-son (URL .mp3)',       type: 'url',       section: 'Music',  placeholder: 'https://... .mp3'                                },
      { key: 'musicStartTime', label: 'DÃ©marrer Ã  (secondes)',      type: 'starttime', section: 'Music'                                                                  },
      { key: 'albumArt',       label: "Pochette / Image d'ambiance",type: 'url',       section: 'Music',  placeholder: 'https://... .jpg'                                },
      { key: 'trackTitle',     label: 'Titre de la bande-son',      type: 'text',      section: 'Music'                                                                  },
      { key: 'trackArtist',    label: 'Compositeur / Artiste',      type: 'text',      section: 'Music'                                                                  },
      { key: 'text2',           label: 'PremiÃ¨re scÃ¨ne (texte)',      type: 'text',      section: 'Story',  placeholder: 'Il Ã©tait une fois...'                            , importance: 'secondary' },
      { key: 'text3',           label: 'DeuxiÃ¨me scÃ¨ne (texte)',      type: 'text',      section: 'Story',  placeholder: 'Une personne exceptionnelle.'                    , importance: 'secondary' },
      { key: 'text4Adjective',  label: 'Mot-clÃ© du film',            type: 'text',      section: 'Story',  placeholder: 'extraordinaire'                                  , importance: 'secondary' },
      { key: 'text5Content',    label: 'Phrase titre du film',       type: 'text',      section: 'Story',  placeholder: 'Notre film, notre histoire.'                     , importance: 'secondary' },
      { key: 'wishHeading',    label: 'Titre du gÃ©nÃ©rique',         type: 'text',      section: 'Wishes', placeholder: 'Joyeux Anniversaire !',           required: true },
      { key: 'wishText',       label: 'Sous-titre du gÃ©nÃ©rique',    type: 'text',      section: 'Wishes', placeholder: 'Avec tout notre amour ðŸŽ¬'                        },
      { key: 'outroText',       label: 'GÃ©nÃ©rique de fin',           type: 'text',      section: 'Outro',  placeholder: 'Fin.'                                            , importance: 'secondary' },
      { key: 'replayText',      label: 'Bouton revoir',              type: 'text',      section: 'Outro',  placeholder: 'â†º Revoir le film'                                , importance: 'secondary' },
    ],
    defaultData: {
      greeting: 'Pour toi,',
      name: 'PrÃ©nom',
      text2: 'Il Ã©tait une fois...',
      text3: 'Une personne exceptionnelle.',
      text4Adjective: 'extraordinaire',
      text5Content: 'Notre film, notre histoire.',
      wishHeading: 'Joyeux Anniversaire !',
      wishText: 'From my heart',
      outroText: 'Fin.',
      replayText: 'â†º Revoir',
    },
    defaultStyle: { primaryColor: '#c9a84c', accentColor: '#e05574', fontFamily: 'Playfair Display', fontSize: 'medium', theme: 'dark' },
  },
];

/* â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€
   Seed runner
â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€ */
async function seed() {
  await mongoose.connect(process.env.MONGO_URI);
  console.log('âœ“ ConnectÃ© Ã  MongoDB\n');

  for (const tpl of TEMPLATES) {
    const { name, ...rest } = tpl;
    await Template.findOneAndUpdate(
      { name },
      { name, ...rest },
      { upsert: true, new: true, setDefaultsOnInsert: true }
    );
    console.log(`âœ“ Template "${name}" mis Ã  jour (${tpl.fields.length} champs)`);
  }

  console.log('\nâ”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€');
  console.log(`${TEMPLATES.length} templates mis Ã  jour avec les labels en franÃ§ais.`);
  console.log('â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€\n');

  await mongoose.disconnect();
  console.log('TerminÃ©.');
}

seed().catch(e => { console.error(e); process.exit(1); });
